// ==============================================================
// Generated by Vitis HLS v2023.1.1
// Copyright 1986-2022 Xilinx, Inc. All Rights Reserved.
// Copyright 2022-2023 Advanced Micro Devices, Inc. All Rights Reserved.
// ==============================================================

`timescale 1 ns / 1 ps 

module fiat_25519_carry_mul_fiat_25519_carry_mul_Pipeline_VITIS_LOOP_39_1 (
        ap_clk,
        ap_rst,
        ap_start,
        ap_done,
        ap_idle,
        ap_ready,
        arg1_r_1_reload,
        arg1_r_2_reload,
        arg1_r_3_reload,
        arg1_r_4_reload,
        arg1_r_5_reload,
        arg1_r_6_reload,
        arg1_r_7_reload,
        arg1_r_8_reload,
        arg1_r_9_reload,
        arg2_r_reload,
        arg2_r_1_reload,
        arg2_r_9_reload,
        arg2_r_8_reload,
        arg2_r_7_reload,
        arg2_r_6_reload,
        arg1_r_reload,
        arg2_r_5_reload,
        arg2_r_4_reload,
        arg2_r_3_reload,
        arg2_r_2_reload,
        add65_1_4229_out,
        add65_1_4229_out_ap_vld,
        add65_1_3228_out,
        add65_1_3228_out_ap_vld,
        add65_1_2227_out,
        add65_1_2227_out_ap_vld,
        add65_1_132226_out,
        add65_1_132226_out_ap_vld,
        add65_1225_out,
        add65_1225_out_ap_vld,
        add65_4224_out,
        add65_4224_out_ap_vld,
        add65_3223_out,
        add65_3223_out_ap_vld,
        add65_2222_out,
        add65_2222_out_ap_vld,
        add65_197221_out,
        add65_197221_out_ap_vld,
        add65220_out,
        add65220_out_ap_vld
);

parameter    ap_ST_fsm_pp0_stage0 = 1'd1;

input   ap_clk;
input   ap_rst;
input   ap_start;
output   ap_done;
output   ap_idle;
output   ap_ready;
input  [31:0] arg1_r_1_reload;
input  [31:0] arg1_r_2_reload;
input  [31:0] arg1_r_3_reload;
input  [31:0] arg1_r_4_reload;
input  [31:0] arg1_r_5_reload;
input  [31:0] arg1_r_6_reload;
input  [31:0] arg1_r_7_reload;
input  [31:0] arg1_r_8_reload;
input  [31:0] arg1_r_9_reload;
input  [31:0] arg2_r_reload;
input  [31:0] arg2_r_1_reload;
input  [31:0] arg2_r_9_reload;
input  [31:0] arg2_r_8_reload;
input  [31:0] arg2_r_7_reload;
input  [31:0] arg2_r_6_reload;
input  [31:0] arg1_r_reload;
input  [31:0] arg2_r_5_reload;
input  [31:0] arg2_r_4_reload;
input  [31:0] arg2_r_3_reload;
input  [31:0] arg2_r_2_reload;
output  [63:0] add65_1_4229_out;
output   add65_1_4229_out_ap_vld;
output  [63:0] add65_1_3228_out;
output   add65_1_3228_out_ap_vld;
output  [63:0] add65_1_2227_out;
output   add65_1_2227_out_ap_vld;
output  [63:0] add65_1_132226_out;
output   add65_1_132226_out_ap_vld;
output  [63:0] add65_1225_out;
output   add65_1225_out_ap_vld;
output  [63:0] add65_4224_out;
output   add65_4224_out_ap_vld;
output  [63:0] add65_3223_out;
output   add65_3223_out_ap_vld;
output  [63:0] add65_2222_out;
output   add65_2222_out_ap_vld;
output  [63:0] add65_197221_out;
output   add65_197221_out_ap_vld;
output  [63:0] add65220_out;
output   add65220_out_ap_vld;

reg ap_idle;
reg add65_1_4229_out_ap_vld;
reg add65_1_3228_out_ap_vld;
reg add65_1_2227_out_ap_vld;
reg add65_1_132226_out_ap_vld;
reg add65_1225_out_ap_vld;
reg add65_4224_out_ap_vld;
reg add65_3223_out_ap_vld;
reg add65_2222_out_ap_vld;
reg add65_197221_out_ap_vld;
reg add65220_out_ap_vld;

(* fsm_encoding = "none" *) reg   [0:0] ap_CS_fsm;
wire    ap_CS_fsm_pp0_stage0;
wire    ap_enable_reg_pp0_iter0;
reg    ap_enable_reg_pp0_iter1;
reg    ap_idle_pp0;
wire    ap_block_state1_pp0_stage0_iter0;
wire    ap_block_state2_pp0_stage0_iter1;
wire    ap_block_pp0_stage0_subdone;
wire   [0:0] tmp_17_fu_661_p3;
reg    ap_condition_exit_pp0_iter0_stage0;
wire    ap_loop_exit_ready;
reg    ap_ready_int;
wire    ap_block_pp0_stage0_11001;
reg   [4:0] i1_1_reg_2374;
wire   [2:0] trunc_ln39_2_fu_673_p1;
reg   [2:0] trunc_ln39_2_reg_2386;
wire   [31:0] tmp_fu_677_p12;
reg   [31:0] tmp_reg_2392;
wire   [0:0] icmp_ln51_fu_709_p2;
reg   [0:0] icmp_ln51_reg_2397;
wire  signed [31:0] tmp_1_fu_730_p12;
reg  signed [31:0] tmp_1_reg_2402;
wire   [31:0] mul_ln52_fu_542_p2;
reg   [31:0] mul_ln52_reg_2409;
wire  signed [31:0] tmp_2_fu_764_p12;
reg  signed [31:0] tmp_2_reg_2414;
wire   [31:0] mul_ln52_1_fu_558_p2;
reg   [31:0] mul_ln52_1_reg_2419;
wire   [0:0] icmp_ln51_1_fu_797_p2;
reg   [0:0] icmp_ln51_1_reg_2424;
wire   [31:0] mul_ln52_2_fu_546_p2;
reg   [31:0] mul_ln52_2_reg_2429;
wire   [31:0] mul_ln52_3_fu_563_p2;
reg   [31:0] mul_ln52_3_reg_2434;
wire   [31:0] tmp_5_fu_879_p12;
reg   [31:0] tmp_5_reg_2439;
wire   [31:0] mul_ln52_4_fu_568_p2;
reg   [31:0] mul_ln52_4_reg_2444;
wire   [31:0] mul_ln52_5_fu_573_p2;
reg   [31:0] mul_ln52_5_reg_2449;
wire   [0:0] icmp_ln51_2_fu_911_p2;
reg   [0:0] icmp_ln51_2_reg_2454;
wire   [31:0] mul_ln52_6_fu_550_p2;
reg   [31:0] mul_ln52_6_reg_2459;
wire   [31:0] mul_ln52_7_fu_578_p2;
reg   [31:0] mul_ln52_7_reg_2464;
wire   [0:0] icmp_ln51_3_fu_999_p2;
reg   [0:0] icmp_ln51_3_reg_2469;
wire   [31:0] mul_ln52_8_fu_554_p2;
reg   [31:0] mul_ln52_8_reg_2474;
wire   [31:0] mul_ln52_9_fu_583_p2;
reg   [31:0] mul_ln52_9_reg_2479;
wire  signed [31:0] tmp_s_fu_1087_p12;
reg  signed [31:0] tmp_s_reg_2484;
wire   [31:0] mul_ln52_10_fu_588_p2;
reg   [31:0] mul_ln52_10_reg_2489;
wire   [31:0] mul_ln52_11_fu_593_p2;
reg   [31:0] mul_ln52_11_reg_2494;
wire   [31:0] mul_ln52_12_fu_598_p2;
reg   [31:0] mul_ln52_12_reg_2499;
wire   [3:0] sub_ln67_fu_1114_p2;
reg   [3:0] sub_ln67_reg_2504;
wire   [0:0] icmp_ln66_fu_1120_p2;
reg   [0:0] icmp_ln66_reg_2509;
wire   [2:0] sub_ln67_1_fu_1126_p2;
reg   [2:0] sub_ln67_1_reg_2515;
wire   [0:0] icmp_ln66_1_fu_1132_p2;
reg   [0:0] icmp_ln66_1_reg_2520;
wire   [2:0] sub_ln67_2_fu_1138_p2;
reg   [2:0] sub_ln67_2_reg_2526;
wire   [0:0] icmp_ln66_2_fu_1144_p2;
reg   [0:0] icmp_ln66_2_reg_2531;
wire   [0:0] icmp_ln66_3_fu_1150_p2;
reg   [0:0] icmp_ln66_3_reg_2537;
reg   [63:0] add65220_fu_164;
wire   [63:0] add_ln67_1_fu_1490_p2;
wire    ap_block_pp0_stage0;
wire    ap_loop_init;
reg   [63:0] add65_197221_fu_168;
wire   [63:0] add_ln67_4_fu_1534_p2;
reg   [63:0] add65_2222_fu_172;
wire   [63:0] add_ln67_8_fu_1603_p2;
reg   [63:0] add65_3223_fu_176;
wire   [63:0] add_ln67_12_fu_1665_p2;
reg   [63:0] add65_4224_fu_180;
wire   [63:0] add_ln67_16_fu_1734_p2;
reg   [63:0] add65_1225_fu_184;
wire   [63:0] add_ln67_20_fu_1884_p2;
reg   [63:0] add65_1_132226_fu_188;
wire   [63:0] add_ln67_24_fu_1953_p2;
reg   [63:0] add65_1_2227_fu_192;
wire   [63:0] add_ln67_28_fu_2015_p2;
reg   [63:0] add65_1_3228_fu_196;
wire   [63:0] add_ln67_32_fu_2083_p2;
reg   [63:0] add65_1_4229_fu_200;
wire   [63:0] add_ln67_35_fu_2113_p2;
reg   [4:0] i1_fu_204;
wire   [4:0] add_ln39_fu_1156_p2;
reg   [4:0] ap_sig_allocacmp_i1_1;
wire    ap_block_pp0_stage0_01001;
wire   [31:0] mul_ln67_fu_398_p0;
wire   [63:0] zext_ln67_fu_1356_p1;
wire   [31:0] mul_ln67_fu_398_p1;
wire   [63:0] zext_ln52_fu_1200_p1;
wire   [31:0] mul_ln67_1_fu_402_p0;
wire   [31:0] mul_ln67_1_fu_402_p1;
wire   [63:0] zext_ln52_5_fu_1261_p1;
wire   [31:0] mul_ln67_2_fu_406_p0;
wire   [31:0] mul_ln67_2_fu_406_p1;
wire   [31:0] mul_ln67_3_fu_410_p0;
wire   [31:0] mul_ln67_3_fu_410_p1;
wire   [31:0] mul_ln67_4_fu_414_p0;
wire   [31:0] mul_ln67_4_fu_414_p1;
wire   [31:0] mul_ln67_5_fu_418_p0;
wire   [31:0] mul_ln67_5_fu_418_p1;
wire   [31:0] mul_ln67_6_fu_422_p0;
wire   [31:0] mul_ln67_6_fu_422_p1;
wire   [31:0] mul_ln67_7_fu_426_p0;
wire   [63:0] zext_ln67_2_fu_1411_p1;
wire   [31:0] mul_ln67_7_fu_426_p1;
wire   [31:0] mul_ln67_8_fu_430_p0;
wire   [63:0] zext_ln52_2_fu_1230_p1;
wire   [31:0] mul_ln67_8_fu_430_p1;
wire   [31:0] mul_ln67_9_fu_434_p0;
wire   [31:0] mul_ln67_9_fu_434_p1;
wire   [31:0] mul_ln67_10_fu_438_p0;
wire   [31:0] mul_ln67_10_fu_438_p1;
wire   [31:0] mul_ln67_11_fu_442_p0;
wire   [31:0] mul_ln67_11_fu_442_p1;
wire   [31:0] mul_ln67_12_fu_446_p0;
wire   [31:0] mul_ln67_12_fu_446_p1;
wire   [31:0] mul_ln67_13_fu_450_p0;
wire   [31:0] mul_ln67_13_fu_450_p1;
wire   [31:0] mul_ln67_14_fu_454_p0;
wire   [31:0] mul_ln67_14_fu_454_p1;
wire   [31:0] mul_ln67_15_fu_458_p0;
wire   [63:0] zext_ln67_4_fu_1468_p1;
wire   [31:0] mul_ln67_15_fu_458_p1;
wire   [31:0] mul_ln67_16_fu_462_p0;
wire   [63:0] zext_ln52_4_fu_1250_p1;
wire   [31:0] mul_ln67_16_fu_462_p1;
wire   [31:0] mul_ln67_17_fu_466_p0;
wire   [31:0] mul_ln67_17_fu_466_p1;
wire   [31:0] mul_ln67_18_fu_470_p0;
wire   [31:0] mul_ln67_18_fu_470_p1;
wire   [31:0] mul_ln67_19_fu_474_p0;
wire   [31:0] mul_ln67_19_fu_474_p1;
wire   [31:0] mul_ln67_20_fu_478_p0;
wire   [31:0] mul_ln67_20_fu_478_p1;
wire   [31:0] mul_ln67_21_fu_482_p0;
wire   [31:0] mul_ln67_21_fu_482_p1;
wire   [31:0] mul_ln67_22_fu_486_p0;
wire   [31:0] mul_ln67_22_fu_486_p1;
wire   [31:0] mul_ln67_23_fu_490_p0;
wire   [63:0] zext_ln67_9_fu_1789_p1;
wire   [31:0] mul_ln67_23_fu_490_p1;
wire   [31:0] mul_ln67_24_fu_494_p0;
wire   [63:0] zext_ln52_9_fu_1299_p1;
wire   [31:0] mul_ln67_24_fu_494_p1;
wire   [31:0] mul_ln67_25_fu_498_p0;
wire   [31:0] mul_ln67_25_fu_498_p1;
wire   [31:0] mul_ln67_26_fu_502_p0;
wire   [31:0] mul_ln67_26_fu_502_p1;
wire   [31:0] mul_ln67_27_fu_506_p0;
wire   [31:0] mul_ln67_27_fu_506_p1;
wire   [31:0] mul_ln67_28_fu_510_p0;
wire   [31:0] mul_ln67_28_fu_510_p1;
wire   [31:0] mul_ln67_29_fu_514_p0;
wire   [31:0] mul_ln67_29_fu_514_p1;
wire   [31:0] mul_ln67_30_fu_518_p0;
wire   [31:0] mul_ln67_30_fu_518_p1;
wire   [31:0] mul_ln67_31_fu_522_p0;
wire   [63:0] zext_ln67_11_fu_1817_p1;
wire   [31:0] mul_ln67_31_fu_522_p1;
wire   [31:0] mul_ln67_32_fu_526_p0;
wire   [63:0] zext_ln52_11_fu_1319_p1;
wire   [31:0] mul_ln67_32_fu_526_p1;
wire   [31:0] mul_ln67_33_fu_530_p0;
wire   [31:0] mul_ln67_33_fu_530_p1;
wire   [31:0] mul_ln67_34_fu_534_p0;
wire   [31:0] mul_ln67_34_fu_534_p1;
wire   [31:0] mul_ln67_35_fu_538_p0;
wire   [31:0] mul_ln67_35_fu_538_p1;
wire  signed [6:0] mul_ln52_fu_542_p1;
wire  signed [31:0] tmp_3_fu_818_p12;
wire  signed [6:0] mul_ln52_2_fu_546_p1;
wire  signed [31:0] tmp_6_fu_932_p12;
wire  signed [6:0] mul_ln52_6_fu_550_p1;
wire  signed [31:0] tmp_8_fu_1020_p12;
wire  signed [6:0] mul_ln52_8_fu_554_p1;
wire   [5:0] mul_ln52_1_fu_558_p1;
wire  signed [31:0] tmp_4_fu_852_p12;
wire   [5:0] mul_ln52_3_fu_563_p1;
wire   [5:0] mul_ln52_4_fu_568_p1;
wire   [5:0] mul_ln52_5_fu_573_p1;
wire  signed [31:0] tmp_7_fu_966_p12;
wire   [5:0] mul_ln52_7_fu_578_p1;
wire  signed [31:0] tmp_9_fu_1054_p12;
wire   [5:0] mul_ln52_9_fu_583_p1;
wire   [6:0] mul_ln52_10_fu_588_p1;
wire   [5:0] mul_ln52_11_fu_593_p1;
wire   [5:0] mul_ln52_12_fu_598_p1;
wire   [3:0] trunc_ln39_fu_669_p1;
wire   [4:0] add_ln51_fu_703_p2;
wire   [3:0] tmp_1_fu_730_p11;
wire   [3:0] tmp_2_fu_764_p11;
wire   [4:0] add_ln51_1_fu_791_p2;
wire   [3:0] tmp_3_fu_818_p11;
wire   [3:0] tmp_4_fu_852_p11;
wire   [4:0] empty_fu_905_p2;
wire   [3:0] tmp_6_fu_932_p11;
wire   [3:0] tmp_7_fu_966_p11;
wire   [4:0] add_ln51_2_fu_993_p2;
wire   [3:0] tmp_8_fu_1020_p11;
wire   [3:0] tmp_9_fu_1054_p11;
wire   [3:0] tmp_s_fu_1087_p11;
wire   [4:0] add_ln52_fu_1225_p2;
wire   [4:0] add_ln52_1_fu_1245_p2;
wire   [4:0] add_ln52_2_fu_1294_p2;
wire   [4:0] add_ln52_3_fu_1314_p2;
wire   [31:0] tmp_10_fu_1342_p11;
wire   [31:0] tmp_11_fu_1362_p10;
wire   [31:0] shl_ln67_fu_1375_p2;
wire   [31:0] select_ln67_fu_1381_p3;
wire   [2:0] tmp_12_fu_1398_p8;
wire   [31:0] tmp_12_fu_1398_p9;
wire   [31:0] tmp_13_fu_1423_p8;
wire   [31:0] shl_ln67_1_fu_1434_p2;
wire   [31:0] select_ln67_1_fu_1440_p3;
wire   [2:0] tmp_14_fu_1457_p6;
wire   [31:0] tmp_14_fu_1457_p7;
wire   [63:0] mul_ln67_fu_398_p2;
wire   [63:0] mul_ln67_1_fu_402_p2;
wire   [63:0] add_ln67_fu_1484_p2;
wire   [63:0] mul_ln67_2_fu_406_p2;
wire   [63:0] select_ln67_4_fu_1496_p3;
wire   [63:0] mul_ln67_3_fu_410_p2;
wire   [63:0] select_ln67_5_fu_1509_p3;
wire   [63:0] mul_ln67_4_fu_414_p2;
wire   [63:0] and_ln67_1_fu_1516_p2;
wire   [63:0] add_ln67_2_fu_1522_p2;
wire   [63:0] and_ln67_fu_1503_p2;
wire   [63:0] add_ln67_3_fu_1528_p2;
wire   [63:0] mul_ln67_5_fu_418_p2;
wire   [63:0] mul_ln67_6_fu_422_p2;
wire   [0:0] icmp_ln67_fu_1417_p2;
wire   [63:0] mul_ln67_7_fu_426_p2;
wire   [63:0] select_ln67_6_fu_1557_p3;
wire   [0:0] icmp_ln52_fu_1235_p2;
wire   [63:0] mul_ln67_8_fu_430_p2;
wire   [63:0] select_ln67_7_fu_1571_p3;
wire   [63:0] and_ln67_5_fu_1579_p2;
wire   [63:0] and_ln67_3_fu_1551_p2;
wire   [63:0] and_ln67_2_fu_1545_p2;
wire   [63:0] and_ln67_4_fu_1565_p2;
wire   [63:0] add_ln67_6_fu_1591_p2;
wire   [63:0] add_ln67_5_fu_1585_p2;
wire   [63:0] add_ln67_7_fu_1597_p2;
wire   [63:0] mul_ln67_9_fu_434_p2;
wire   [63:0] mul_ln67_10_fu_438_p2;
wire   [63:0] mul_ln67_11_fu_442_p2;
wire   [63:0] select_ln67_8_fu_1621_p3;
wire   [63:0] mul_ln67_12_fu_446_p2;
wire   [63:0] select_ln67_9_fu_1634_p3;
wire   [63:0] and_ln67_9_fu_1641_p2;
wire   [63:0] and_ln67_7_fu_1615_p2;
wire   [63:0] and_ln67_6_fu_1609_p2;
wire   [63:0] and_ln67_8_fu_1628_p2;
wire   [63:0] add_ln67_10_fu_1653_p2;
wire   [63:0] add_ln67_9_fu_1647_p2;
wire   [63:0] add_ln67_11_fu_1659_p2;
wire   [63:0] mul_ln67_13_fu_450_p2;
wire   [63:0] mul_ln67_14_fu_454_p2;
wire   [0:0] icmp_ln67_1_fu_1474_p2;
wire   [63:0] mul_ln67_15_fu_458_p2;
wire   [63:0] select_ln67_10_fu_1688_p3;
wire   [0:0] icmp_ln52_1_fu_1255_p2;
wire   [63:0] mul_ln67_16_fu_462_p2;
wire   [63:0] select_ln67_11_fu_1702_p3;
wire   [63:0] and_ln67_11_fu_1682_p2;
wire   [63:0] and_ln67_13_fu_1710_p2;
wire   [63:0] and_ln67_10_fu_1676_p2;
wire   [63:0] and_ln67_12_fu_1696_p2;
wire   [63:0] add_ln67_14_fu_1722_p2;
wire   [63:0] add_ln67_13_fu_1716_p2;
wire   [63:0] add_ln67_15_fu_1728_p2;
wire   [1:0] trunc_ln39_1_fu_1197_p1;
wire   [1:0] tmp_15_fu_1746_p5;
wire   [31:0] tmp_15_fu_1746_p6;
wire   [31:0] shl_ln67_2_fu_1756_p2;
wire   [31:0] select_ln67_2_fu_1762_p3;
wire   [1:0] tmp_16_fu_1780_p4;
wire   [31:0] tmp_16_fu_1780_p5;
wire   [31:0] shl_ln67_3_fu_1801_p2;
wire   [31:0] select_ln67_3_fu_1806_p3;
wire   [63:0] mul_ln67_17_fu_466_p2;
wire   [63:0] mul_ln67_18_fu_470_p2;
wire   [63:0] mul_ln67_19_fu_474_p2;
wire   [63:0] select_ln67_12_fu_1840_p3;
wire   [63:0] mul_ln67_20_fu_478_p2;
wire   [63:0] select_ln67_13_fu_1853_p3;
wire   [63:0] and_ln67_15_fu_1834_p2;
wire   [63:0] and_ln67_17_fu_1860_p2;
wire   [63:0] and_ln67_14_fu_1828_p2;
wire   [63:0] and_ln67_16_fu_1847_p2;
wire   [63:0] add_ln67_18_fu_1872_p2;
wire   [63:0] add_ln67_17_fu_1866_p2;
wire   [63:0] add_ln67_19_fu_1878_p2;
wire   [63:0] mul_ln67_21_fu_482_p2;
wire   [63:0] mul_ln67_22_fu_486_p2;
wire   [0:0] icmp_ln67_2_fu_1795_p2;
wire   [63:0] mul_ln67_23_fu_490_p2;
wire   [63:0] select_ln67_14_fu_1907_p3;
wire   [0:0] icmp_ln52_2_fu_1304_p2;
wire   [63:0] mul_ln67_24_fu_494_p2;
wire   [63:0] select_ln67_15_fu_1921_p3;
wire   [63:0] and_ln67_19_fu_1901_p2;
wire   [63:0] and_ln67_21_fu_1929_p2;
wire   [63:0] and_ln67_18_fu_1895_p2;
wire   [63:0] and_ln67_20_fu_1915_p2;
wire   [63:0] add_ln67_22_fu_1941_p2;
wire   [63:0] add_ln67_21_fu_1935_p2;
wire   [63:0] add_ln67_23_fu_1947_p2;
wire   [63:0] mul_ln67_25_fu_498_p2;
wire   [63:0] mul_ln67_26_fu_502_p2;
wire   [63:0] mul_ln67_27_fu_506_p2;
wire   [63:0] select_ln67_16_fu_1971_p3;
wire   [63:0] mul_ln67_28_fu_510_p2;
wire   [63:0] select_ln67_17_fu_1984_p3;
wire   [63:0] and_ln67_24_fu_1978_p2;
wire   [63:0] and_ln67_23_fu_1965_p2;
wire   [63:0] and_ln67_25_fu_1991_p2;
wire   [63:0] and_ln67_22_fu_1959_p2;
wire   [63:0] add_ln67_26_fu_2003_p2;
wire   [63:0] add_ln67_25_fu_1997_p2;
wire   [63:0] add_ln67_27_fu_2009_p2;
wire   [63:0] mul_ln67_29_fu_514_p2;
wire   [63:0] mul_ln67_30_fu_518_p2;
wire   [0:0] icmp_ln67_3_fu_1822_p2;
wire   [63:0] mul_ln67_31_fu_522_p2;
wire   [63:0] select_ln67_18_fu_2037_p3;
wire   [0:0] icmp_ln52_3_fu_1324_p2;
wire   [63:0] mul_ln67_32_fu_526_p2;
wire   [63:0] select_ln67_19_fu_2051_p3;
wire   [63:0] and_ln67_28_fu_2045_p2;
wire   [63:0] and_ln67_26_fu_2025_p2;
wire   [63:0] and_ln67_27_fu_2031_p2;
wire   [63:0] and_ln67_29_fu_2059_p2;
wire   [63:0] add_ln67_30_fu_2071_p2;
wire   [63:0] add_ln67_29_fu_2065_p2;
wire   [63:0] add_ln67_31_fu_2077_p2;
wire   [63:0] mul_ln67_33_fu_530_p2;
wire   [63:0] mul_ln67_34_fu_534_p2;
wire   [63:0] and_ln67_31_fu_2095_p2;
wire   [63:0] mul_ln67_35_fu_538_p2;
wire   [63:0] add_ln67_33_fu_2101_p2;
wire   [63:0] and_ln67_30_fu_2089_p2;
wire   [63:0] add_ln67_34_fu_2107_p2;
reg    ap_done_reg;
wire    ap_continue_int;
reg    ap_done_int;
reg   [0:0] ap_NS_fsm;
wire    ap_enable_pp0;
wire    ap_start_int;
wire  signed [31:0] mul_ln52_2_fu_546_p10;
wire  signed [31:0] mul_ln52_6_fu_550_p10;
wire  signed [31:0] mul_ln52_8_fu_554_p10;
wire  signed [31:0] mul_ln52_fu_542_p10;
wire   [63:0] mul_ln67_11_fu_442_p00;
wire   [63:0] mul_ln67_12_fu_446_p00;
wire   [63:0] mul_ln67_13_fu_450_p00;
wire   [63:0] mul_ln67_14_fu_454_p10;
wire   [63:0] mul_ln67_19_fu_474_p00;
wire   [63:0] mul_ln67_1_fu_402_p00;
wire   [63:0] mul_ln67_20_fu_478_p00;
wire   [63:0] mul_ln67_21_fu_482_p00;
wire   [63:0] mul_ln67_22_fu_486_p00;
wire   [63:0] mul_ln67_27_fu_506_p00;
wire   [63:0] mul_ln67_28_fu_510_p00;
wire   [63:0] mul_ln67_29_fu_514_p10;
wire   [63:0] mul_ln67_2_fu_406_p00;
wire   [63:0] mul_ln67_30_fu_518_p00;
wire   [63:0] mul_ln67_35_fu_538_p00;
wire   [63:0] mul_ln67_3_fu_410_p00;
wire   [63:0] mul_ln67_5_fu_418_p00;
wire   [63:0] mul_ln67_6_fu_422_p10;
wire    ap_ce_reg;

// power-on initialization
initial begin
#0 ap_CS_fsm = 1'd1;
#0 ap_enable_reg_pp0_iter1 = 1'b0;
#0 ap_done_reg = 1'b0;
end

fiat_25519_carry_mul_mul_32ns_32ns_64_1_1 #(
    .ID( 1 ),
    .NUM_STAGE( 1 ),
    .din0_WIDTH( 32 ),
    .din1_WIDTH( 32 ),
    .dout_WIDTH( 64 ))
mul_32ns_32ns_64_1_1_U25(
    .din0(mul_ln67_fu_398_p0),
    .din1(mul_ln67_fu_398_p1),
    .dout(mul_ln67_fu_398_p2)
);

fiat_25519_carry_mul_mul_32ns_32ns_64_1_1 #(
    .ID( 1 ),
    .NUM_STAGE( 1 ),
    .din0_WIDTH( 32 ),
    .din1_WIDTH( 32 ),
    .dout_WIDTH( 64 ))
mul_32ns_32ns_64_1_1_U26(
    .din0(mul_ln67_1_fu_402_p0),
    .din1(mul_ln67_1_fu_402_p1),
    .dout(mul_ln67_1_fu_402_p2)
);

fiat_25519_carry_mul_mul_32ns_32ns_64_1_1 #(
    .ID( 1 ),
    .NUM_STAGE( 1 ),
    .din0_WIDTH( 32 ),
    .din1_WIDTH( 32 ),
    .dout_WIDTH( 64 ))
mul_32ns_32ns_64_1_1_U27(
    .din0(mul_ln67_2_fu_406_p0),
    .din1(mul_ln67_2_fu_406_p1),
    .dout(mul_ln67_2_fu_406_p2)
);

fiat_25519_carry_mul_mul_32ns_32ns_64_1_1 #(
    .ID( 1 ),
    .NUM_STAGE( 1 ),
    .din0_WIDTH( 32 ),
    .din1_WIDTH( 32 ),
    .dout_WIDTH( 64 ))
mul_32ns_32ns_64_1_1_U28(
    .din0(mul_ln67_3_fu_410_p0),
    .din1(mul_ln67_3_fu_410_p1),
    .dout(mul_ln67_3_fu_410_p2)
);

fiat_25519_carry_mul_mul_32ns_32ns_64_1_1 #(
    .ID( 1 ),
    .NUM_STAGE( 1 ),
    .din0_WIDTH( 32 ),
    .din1_WIDTH( 32 ),
    .dout_WIDTH( 64 ))
mul_32ns_32ns_64_1_1_U29(
    .din0(mul_ln67_4_fu_414_p0),
    .din1(mul_ln67_4_fu_414_p1),
    .dout(mul_ln67_4_fu_414_p2)
);

fiat_25519_carry_mul_mul_32ns_32ns_64_1_1 #(
    .ID( 1 ),
    .NUM_STAGE( 1 ),
    .din0_WIDTH( 32 ),
    .din1_WIDTH( 32 ),
    .dout_WIDTH( 64 ))
mul_32ns_32ns_64_1_1_U30(
    .din0(mul_ln67_5_fu_418_p0),
    .din1(mul_ln67_5_fu_418_p1),
    .dout(mul_ln67_5_fu_418_p2)
);

fiat_25519_carry_mul_mul_32ns_32ns_64_1_1 #(
    .ID( 1 ),
    .NUM_STAGE( 1 ),
    .din0_WIDTH( 32 ),
    .din1_WIDTH( 32 ),
    .dout_WIDTH( 64 ))
mul_32ns_32ns_64_1_1_U31(
    .din0(mul_ln67_6_fu_422_p0),
    .din1(mul_ln67_6_fu_422_p1),
    .dout(mul_ln67_6_fu_422_p2)
);

fiat_25519_carry_mul_mul_32ns_32ns_64_1_1 #(
    .ID( 1 ),
    .NUM_STAGE( 1 ),
    .din0_WIDTH( 32 ),
    .din1_WIDTH( 32 ),
    .dout_WIDTH( 64 ))
mul_32ns_32ns_64_1_1_U32(
    .din0(mul_ln67_7_fu_426_p0),
    .din1(mul_ln67_7_fu_426_p1),
    .dout(mul_ln67_7_fu_426_p2)
);

fiat_25519_carry_mul_mul_32ns_32ns_64_1_1 #(
    .ID( 1 ),
    .NUM_STAGE( 1 ),
    .din0_WIDTH( 32 ),
    .din1_WIDTH( 32 ),
    .dout_WIDTH( 64 ))
mul_32ns_32ns_64_1_1_U33(
    .din0(mul_ln67_8_fu_430_p0),
    .din1(mul_ln67_8_fu_430_p1),
    .dout(mul_ln67_8_fu_430_p2)
);

fiat_25519_carry_mul_mul_32ns_32ns_64_1_1 #(
    .ID( 1 ),
    .NUM_STAGE( 1 ),
    .din0_WIDTH( 32 ),
    .din1_WIDTH( 32 ),
    .dout_WIDTH( 64 ))
mul_32ns_32ns_64_1_1_U34(
    .din0(mul_ln67_9_fu_434_p0),
    .din1(mul_ln67_9_fu_434_p1),
    .dout(mul_ln67_9_fu_434_p2)
);

fiat_25519_carry_mul_mul_32ns_32ns_64_1_1 #(
    .ID( 1 ),
    .NUM_STAGE( 1 ),
    .din0_WIDTH( 32 ),
    .din1_WIDTH( 32 ),
    .dout_WIDTH( 64 ))
mul_32ns_32ns_64_1_1_U35(
    .din0(mul_ln67_10_fu_438_p0),
    .din1(mul_ln67_10_fu_438_p1),
    .dout(mul_ln67_10_fu_438_p2)
);

fiat_25519_carry_mul_mul_32ns_32ns_64_1_1 #(
    .ID( 1 ),
    .NUM_STAGE( 1 ),
    .din0_WIDTH( 32 ),
    .din1_WIDTH( 32 ),
    .dout_WIDTH( 64 ))
mul_32ns_32ns_64_1_1_U36(
    .din0(mul_ln67_11_fu_442_p0),
    .din1(mul_ln67_11_fu_442_p1),
    .dout(mul_ln67_11_fu_442_p2)
);

fiat_25519_carry_mul_mul_32ns_32ns_64_1_1 #(
    .ID( 1 ),
    .NUM_STAGE( 1 ),
    .din0_WIDTH( 32 ),
    .din1_WIDTH( 32 ),
    .dout_WIDTH( 64 ))
mul_32ns_32ns_64_1_1_U37(
    .din0(mul_ln67_12_fu_446_p0),
    .din1(mul_ln67_12_fu_446_p1),
    .dout(mul_ln67_12_fu_446_p2)
);

fiat_25519_carry_mul_mul_32ns_32ns_64_1_1 #(
    .ID( 1 ),
    .NUM_STAGE( 1 ),
    .din0_WIDTH( 32 ),
    .din1_WIDTH( 32 ),
    .dout_WIDTH( 64 ))
mul_32ns_32ns_64_1_1_U38(
    .din0(mul_ln67_13_fu_450_p0),
    .din1(mul_ln67_13_fu_450_p1),
    .dout(mul_ln67_13_fu_450_p2)
);

fiat_25519_carry_mul_mul_32ns_32ns_64_1_1 #(
    .ID( 1 ),
    .NUM_STAGE( 1 ),
    .din0_WIDTH( 32 ),
    .din1_WIDTH( 32 ),
    .dout_WIDTH( 64 ))
mul_32ns_32ns_64_1_1_U39(
    .din0(mul_ln67_14_fu_454_p0),
    .din1(mul_ln67_14_fu_454_p1),
    .dout(mul_ln67_14_fu_454_p2)
);

fiat_25519_carry_mul_mul_32ns_32ns_64_1_1 #(
    .ID( 1 ),
    .NUM_STAGE( 1 ),
    .din0_WIDTH( 32 ),
    .din1_WIDTH( 32 ),
    .dout_WIDTH( 64 ))
mul_32ns_32ns_64_1_1_U40(
    .din0(mul_ln67_15_fu_458_p0),
    .din1(mul_ln67_15_fu_458_p1),
    .dout(mul_ln67_15_fu_458_p2)
);

fiat_25519_carry_mul_mul_32ns_32ns_64_1_1 #(
    .ID( 1 ),
    .NUM_STAGE( 1 ),
    .din0_WIDTH( 32 ),
    .din1_WIDTH( 32 ),
    .dout_WIDTH( 64 ))
mul_32ns_32ns_64_1_1_U41(
    .din0(mul_ln67_16_fu_462_p0),
    .din1(mul_ln67_16_fu_462_p1),
    .dout(mul_ln67_16_fu_462_p2)
);

fiat_25519_carry_mul_mul_32ns_32ns_64_1_1 #(
    .ID( 1 ),
    .NUM_STAGE( 1 ),
    .din0_WIDTH( 32 ),
    .din1_WIDTH( 32 ),
    .dout_WIDTH( 64 ))
mul_32ns_32ns_64_1_1_U42(
    .din0(mul_ln67_17_fu_466_p0),
    .din1(mul_ln67_17_fu_466_p1),
    .dout(mul_ln67_17_fu_466_p2)
);

fiat_25519_carry_mul_mul_32ns_32ns_64_1_1 #(
    .ID( 1 ),
    .NUM_STAGE( 1 ),
    .din0_WIDTH( 32 ),
    .din1_WIDTH( 32 ),
    .dout_WIDTH( 64 ))
mul_32ns_32ns_64_1_1_U43(
    .din0(mul_ln67_18_fu_470_p0),
    .din1(mul_ln67_18_fu_470_p1),
    .dout(mul_ln67_18_fu_470_p2)
);

fiat_25519_carry_mul_mul_32ns_32ns_64_1_1 #(
    .ID( 1 ),
    .NUM_STAGE( 1 ),
    .din0_WIDTH( 32 ),
    .din1_WIDTH( 32 ),
    .dout_WIDTH( 64 ))
mul_32ns_32ns_64_1_1_U44(
    .din0(mul_ln67_19_fu_474_p0),
    .din1(mul_ln67_19_fu_474_p1),
    .dout(mul_ln67_19_fu_474_p2)
);

fiat_25519_carry_mul_mul_32ns_32ns_64_1_1 #(
    .ID( 1 ),
    .NUM_STAGE( 1 ),
    .din0_WIDTH( 32 ),
    .din1_WIDTH( 32 ),
    .dout_WIDTH( 64 ))
mul_32ns_32ns_64_1_1_U45(
    .din0(mul_ln67_20_fu_478_p0),
    .din1(mul_ln67_20_fu_478_p1),
    .dout(mul_ln67_20_fu_478_p2)
);

fiat_25519_carry_mul_mul_32ns_32ns_64_1_1 #(
    .ID( 1 ),
    .NUM_STAGE( 1 ),
    .din0_WIDTH( 32 ),
    .din1_WIDTH( 32 ),
    .dout_WIDTH( 64 ))
mul_32ns_32ns_64_1_1_U46(
    .din0(mul_ln67_21_fu_482_p0),
    .din1(mul_ln67_21_fu_482_p1),
    .dout(mul_ln67_21_fu_482_p2)
);

fiat_25519_carry_mul_mul_32ns_32ns_64_1_1 #(
    .ID( 1 ),
    .NUM_STAGE( 1 ),
    .din0_WIDTH( 32 ),
    .din1_WIDTH( 32 ),
    .dout_WIDTH( 64 ))
mul_32ns_32ns_64_1_1_U47(
    .din0(mul_ln67_22_fu_486_p0),
    .din1(mul_ln67_22_fu_486_p1),
    .dout(mul_ln67_22_fu_486_p2)
);

fiat_25519_carry_mul_mul_32ns_32ns_64_1_1 #(
    .ID( 1 ),
    .NUM_STAGE( 1 ),
    .din0_WIDTH( 32 ),
    .din1_WIDTH( 32 ),
    .dout_WIDTH( 64 ))
mul_32ns_32ns_64_1_1_U48(
    .din0(mul_ln67_23_fu_490_p0),
    .din1(mul_ln67_23_fu_490_p1),
    .dout(mul_ln67_23_fu_490_p2)
);

fiat_25519_carry_mul_mul_32ns_32ns_64_1_1 #(
    .ID( 1 ),
    .NUM_STAGE( 1 ),
    .din0_WIDTH( 32 ),
    .din1_WIDTH( 32 ),
    .dout_WIDTH( 64 ))
mul_32ns_32ns_64_1_1_U49(
    .din0(mul_ln67_24_fu_494_p0),
    .din1(mul_ln67_24_fu_494_p1),
    .dout(mul_ln67_24_fu_494_p2)
);

fiat_25519_carry_mul_mul_32ns_32ns_64_1_1 #(
    .ID( 1 ),
    .NUM_STAGE( 1 ),
    .din0_WIDTH( 32 ),
    .din1_WIDTH( 32 ),
    .dout_WIDTH( 64 ))
mul_32ns_32ns_64_1_1_U50(
    .din0(mul_ln67_25_fu_498_p0),
    .din1(mul_ln67_25_fu_498_p1),
    .dout(mul_ln67_25_fu_498_p2)
);

fiat_25519_carry_mul_mul_32ns_32ns_64_1_1 #(
    .ID( 1 ),
    .NUM_STAGE( 1 ),
    .din0_WIDTH( 32 ),
    .din1_WIDTH( 32 ),
    .dout_WIDTH( 64 ))
mul_32ns_32ns_64_1_1_U51(
    .din0(mul_ln67_26_fu_502_p0),
    .din1(mul_ln67_26_fu_502_p1),
    .dout(mul_ln67_26_fu_502_p2)
);

fiat_25519_carry_mul_mul_32ns_32ns_64_1_1 #(
    .ID( 1 ),
    .NUM_STAGE( 1 ),
    .din0_WIDTH( 32 ),
    .din1_WIDTH( 32 ),
    .dout_WIDTH( 64 ))
mul_32ns_32ns_64_1_1_U52(
    .din0(mul_ln67_27_fu_506_p0),
    .din1(mul_ln67_27_fu_506_p1),
    .dout(mul_ln67_27_fu_506_p2)
);

fiat_25519_carry_mul_mul_32ns_32ns_64_1_1 #(
    .ID( 1 ),
    .NUM_STAGE( 1 ),
    .din0_WIDTH( 32 ),
    .din1_WIDTH( 32 ),
    .dout_WIDTH( 64 ))
mul_32ns_32ns_64_1_1_U53(
    .din0(mul_ln67_28_fu_510_p0),
    .din1(mul_ln67_28_fu_510_p1),
    .dout(mul_ln67_28_fu_510_p2)
);

fiat_25519_carry_mul_mul_32ns_32ns_64_1_1 #(
    .ID( 1 ),
    .NUM_STAGE( 1 ),
    .din0_WIDTH( 32 ),
    .din1_WIDTH( 32 ),
    .dout_WIDTH( 64 ))
mul_32ns_32ns_64_1_1_U54(
    .din0(mul_ln67_29_fu_514_p0),
    .din1(mul_ln67_29_fu_514_p1),
    .dout(mul_ln67_29_fu_514_p2)
);

fiat_25519_carry_mul_mul_32ns_32ns_64_1_1 #(
    .ID( 1 ),
    .NUM_STAGE( 1 ),
    .din0_WIDTH( 32 ),
    .din1_WIDTH( 32 ),
    .dout_WIDTH( 64 ))
mul_32ns_32ns_64_1_1_U55(
    .din0(mul_ln67_30_fu_518_p0),
    .din1(mul_ln67_30_fu_518_p1),
    .dout(mul_ln67_30_fu_518_p2)
);

fiat_25519_carry_mul_mul_32ns_32ns_64_1_1 #(
    .ID( 1 ),
    .NUM_STAGE( 1 ),
    .din0_WIDTH( 32 ),
    .din1_WIDTH( 32 ),
    .dout_WIDTH( 64 ))
mul_32ns_32ns_64_1_1_U56(
    .din0(mul_ln67_31_fu_522_p0),
    .din1(mul_ln67_31_fu_522_p1),
    .dout(mul_ln67_31_fu_522_p2)
);

fiat_25519_carry_mul_mul_32ns_32ns_64_1_1 #(
    .ID( 1 ),
    .NUM_STAGE( 1 ),
    .din0_WIDTH( 32 ),
    .din1_WIDTH( 32 ),
    .dout_WIDTH( 64 ))
mul_32ns_32ns_64_1_1_U57(
    .din0(mul_ln67_32_fu_526_p0),
    .din1(mul_ln67_32_fu_526_p1),
    .dout(mul_ln67_32_fu_526_p2)
);

fiat_25519_carry_mul_mul_32ns_32ns_64_1_1 #(
    .ID( 1 ),
    .NUM_STAGE( 1 ),
    .din0_WIDTH( 32 ),
    .din1_WIDTH( 32 ),
    .dout_WIDTH( 64 ))
mul_32ns_32ns_64_1_1_U58(
    .din0(mul_ln67_33_fu_530_p0),
    .din1(mul_ln67_33_fu_530_p1),
    .dout(mul_ln67_33_fu_530_p2)
);

fiat_25519_carry_mul_mul_32ns_32ns_64_1_1 #(
    .ID( 1 ),
    .NUM_STAGE( 1 ),
    .din0_WIDTH( 32 ),
    .din1_WIDTH( 32 ),
    .dout_WIDTH( 64 ))
mul_32ns_32ns_64_1_1_U59(
    .din0(mul_ln67_34_fu_534_p0),
    .din1(mul_ln67_34_fu_534_p1),
    .dout(mul_ln67_34_fu_534_p2)
);

fiat_25519_carry_mul_mul_32ns_32ns_64_1_1 #(
    .ID( 1 ),
    .NUM_STAGE( 1 ),
    .din0_WIDTH( 32 ),
    .din1_WIDTH( 32 ),
    .dout_WIDTH( 64 ))
mul_32ns_32ns_64_1_1_U60(
    .din0(mul_ln67_35_fu_538_p0),
    .din1(mul_ln67_35_fu_538_p1),
    .dout(mul_ln67_35_fu_538_p2)
);

fiat_25519_carry_mul_mul_32s_7s_32_1_1 #(
    .ID( 1 ),
    .NUM_STAGE( 1 ),
    .din0_WIDTH( 32 ),
    .din1_WIDTH( 7 ),
    .dout_WIDTH( 32 ))
mul_32s_7s_32_1_1_U61(
    .din0(tmp_1_fu_730_p12),
    .din1(mul_ln52_fu_542_p1),
    .dout(mul_ln52_fu_542_p2)
);

fiat_25519_carry_mul_mul_32s_7s_32_1_1 #(
    .ID( 1 ),
    .NUM_STAGE( 1 ),
    .din0_WIDTH( 32 ),
    .din1_WIDTH( 7 ),
    .dout_WIDTH( 32 ))
mul_32s_7s_32_1_1_U62(
    .din0(tmp_3_fu_818_p12),
    .din1(mul_ln52_2_fu_546_p1),
    .dout(mul_ln52_2_fu_546_p2)
);

fiat_25519_carry_mul_mul_32s_7s_32_1_1 #(
    .ID( 1 ),
    .NUM_STAGE( 1 ),
    .din0_WIDTH( 32 ),
    .din1_WIDTH( 7 ),
    .dout_WIDTH( 32 ))
mul_32s_7s_32_1_1_U63(
    .din0(tmp_6_fu_932_p12),
    .din1(mul_ln52_6_fu_550_p1),
    .dout(mul_ln52_6_fu_550_p2)
);

fiat_25519_carry_mul_mul_32s_7s_32_1_1 #(
    .ID( 1 ),
    .NUM_STAGE( 1 ),
    .din0_WIDTH( 32 ),
    .din1_WIDTH( 7 ),
    .dout_WIDTH( 32 ))
mul_32s_7s_32_1_1_U64(
    .din0(tmp_8_fu_1020_p12),
    .din1(mul_ln52_8_fu_554_p1),
    .dout(mul_ln52_8_fu_554_p2)
);

fiat_25519_carry_mul_mul_32s_6ns_32_1_1 #(
    .ID( 1 ),
    .NUM_STAGE( 1 ),
    .din0_WIDTH( 32 ),
    .din1_WIDTH( 6 ),
    .dout_WIDTH( 32 ))
mul_32s_6ns_32_1_1_U65(
    .din0(tmp_2_fu_764_p12),
    .din1(mul_ln52_1_fu_558_p1),
    .dout(mul_ln52_1_fu_558_p2)
);

fiat_25519_carry_mul_mul_32s_6ns_32_1_1 #(
    .ID( 1 ),
    .NUM_STAGE( 1 ),
    .din0_WIDTH( 32 ),
    .din1_WIDTH( 6 ),
    .dout_WIDTH( 32 ))
mul_32s_6ns_32_1_1_U66(
    .din0(tmp_4_fu_852_p12),
    .din1(mul_ln52_3_fu_563_p1),
    .dout(mul_ln52_3_fu_563_p2)
);

fiat_25519_carry_mul_mul_32s_6ns_32_1_1 #(
    .ID( 1 ),
    .NUM_STAGE( 1 ),
    .din0_WIDTH( 32 ),
    .din1_WIDTH( 6 ),
    .dout_WIDTH( 32 ))
mul_32s_6ns_32_1_1_U67(
    .din0(tmp_1_fu_730_p12),
    .din1(mul_ln52_4_fu_568_p1),
    .dout(mul_ln52_4_fu_568_p2)
);

fiat_25519_carry_mul_mul_32s_6ns_32_1_1 #(
    .ID( 1 ),
    .NUM_STAGE( 1 ),
    .din0_WIDTH( 32 ),
    .din1_WIDTH( 6 ),
    .dout_WIDTH( 32 ))
mul_32s_6ns_32_1_1_U68(
    .din0(tmp_3_fu_818_p12),
    .din1(mul_ln52_5_fu_573_p1),
    .dout(mul_ln52_5_fu_573_p2)
);

fiat_25519_carry_mul_mul_32s_6ns_32_1_1 #(
    .ID( 1 ),
    .NUM_STAGE( 1 ),
    .din0_WIDTH( 32 ),
    .din1_WIDTH( 6 ),
    .dout_WIDTH( 32 ))
mul_32s_6ns_32_1_1_U69(
    .din0(tmp_7_fu_966_p12),
    .din1(mul_ln52_7_fu_578_p1),
    .dout(mul_ln52_7_fu_578_p2)
);

fiat_25519_carry_mul_mul_32s_6ns_32_1_1 #(
    .ID( 1 ),
    .NUM_STAGE( 1 ),
    .din0_WIDTH( 32 ),
    .din1_WIDTH( 6 ),
    .dout_WIDTH( 32 ))
mul_32s_6ns_32_1_1_U70(
    .din0(tmp_9_fu_1054_p12),
    .din1(mul_ln52_9_fu_583_p1),
    .dout(mul_ln52_9_fu_583_p2)
);

fiat_25519_carry_mul_mul_32s_7ns_32_1_1 #(
    .ID( 1 ),
    .NUM_STAGE( 1 ),
    .din0_WIDTH( 32 ),
    .din1_WIDTH( 7 ),
    .dout_WIDTH( 32 ))
mul_32s_7ns_32_1_1_U71(
    .din0(tmp_s_fu_1087_p12),
    .din1(mul_ln52_10_fu_588_p1),
    .dout(mul_ln52_10_fu_588_p2)
);

fiat_25519_carry_mul_mul_32s_6ns_32_1_1 #(
    .ID( 1 ),
    .NUM_STAGE( 1 ),
    .din0_WIDTH( 32 ),
    .din1_WIDTH( 6 ),
    .dout_WIDTH( 32 ))
mul_32s_6ns_32_1_1_U72(
    .din0(tmp_6_fu_932_p12),
    .din1(mul_ln52_11_fu_593_p1),
    .dout(mul_ln52_11_fu_593_p2)
);

fiat_25519_carry_mul_mul_32s_6ns_32_1_1 #(
    .ID( 1 ),
    .NUM_STAGE( 1 ),
    .din0_WIDTH( 32 ),
    .din1_WIDTH( 6 ),
    .dout_WIDTH( 32 ))
mul_32s_6ns_32_1_1_U73(
    .din0(tmp_8_fu_1020_p12),
    .din1(mul_ln52_12_fu_598_p1),
    .dout(mul_ln52_12_fu_598_p2)
);

fiat_25519_carry_mul_mux_10_4_32_1_1 #(
    .ID( 1 ),
    .NUM_STAGE( 1 ),
    .din0_WIDTH( 32 ),
    .din1_WIDTH( 32 ),
    .din2_WIDTH( 32 ),
    .din3_WIDTH( 32 ),
    .din4_WIDTH( 32 ),
    .din5_WIDTH( 32 ),
    .din6_WIDTH( 32 ),
    .din7_WIDTH( 32 ),
    .din8_WIDTH( 32 ),
    .din9_WIDTH( 32 ),
    .din10_WIDTH( 4 ),
    .dout_WIDTH( 32 ))
mux_10_4_32_1_1_U74(
    .din0(32'd0),
    .din1(arg1_r_1_reload),
    .din2(arg1_r_2_reload),
    .din3(arg1_r_3_reload),
    .din4(arg1_r_4_reload),
    .din5(arg1_r_5_reload),
    .din6(arg1_r_6_reload),
    .din7(arg1_r_7_reload),
    .din8(arg1_r_8_reload),
    .din9(arg1_r_9_reload),
    .din10(trunc_ln39_fu_669_p1),
    .dout(tmp_fu_677_p12)
);

fiat_25519_carry_mul_mux_10_4_32_1_1 #(
    .ID( 1 ),
    .NUM_STAGE( 1 ),
    .din0_WIDTH( 32 ),
    .din1_WIDTH( 32 ),
    .din2_WIDTH( 32 ),
    .din3_WIDTH( 32 ),
    .din4_WIDTH( 32 ),
    .din5_WIDTH( 32 ),
    .din6_WIDTH( 32 ),
    .din7_WIDTH( 32 ),
    .din8_WIDTH( 32 ),
    .din9_WIDTH( 32 ),
    .din10_WIDTH( 4 ),
    .dout_WIDTH( 32 ))
mux_10_4_32_1_1_U75(
    .din0(arg2_r_reload),
    .din1(arg2_r_1_reload),
    .din2(32'd0),
    .din3(32'd0),
    .din4(32'd0),
    .din5(32'd0),
    .din6(32'd0),
    .din7(32'd0),
    .din8(32'd0),
    .din9(arg2_r_9_reload),
    .din10(tmp_1_fu_730_p11),
    .dout(tmp_1_fu_730_p12)
);

fiat_25519_carry_mul_mux_10_4_32_1_1 #(
    .ID( 1 ),
    .NUM_STAGE( 1 ),
    .din0_WIDTH( 32 ),
    .din1_WIDTH( 32 ),
    .din2_WIDTH( 32 ),
    .din3_WIDTH( 32 ),
    .din4_WIDTH( 32 ),
    .din5_WIDTH( 32 ),
    .din6_WIDTH( 32 ),
    .din7_WIDTH( 32 ),
    .din8_WIDTH( 32 ),
    .din9_WIDTH( 32 ),
    .din10_WIDTH( 4 ),
    .dout_WIDTH( 32 ))
mux_10_4_32_1_1_U76(
    .din0(arg2_r_reload),
    .din1(32'd0),
    .din2(32'd0),
    .din3(32'd0),
    .din4(32'd0),
    .din5(32'd0),
    .din6(32'd0),
    .din7(32'd0),
    .din8(arg2_r_8_reload),
    .din9(arg2_r_9_reload),
    .din10(tmp_2_fu_764_p11),
    .dout(tmp_2_fu_764_p12)
);

fiat_25519_carry_mul_mux_10_4_32_1_1 #(
    .ID( 1 ),
    .NUM_STAGE( 1 ),
    .din0_WIDTH( 32 ),
    .din1_WIDTH( 32 ),
    .din2_WIDTH( 32 ),
    .din3_WIDTH( 32 ),
    .din4_WIDTH( 32 ),
    .din5_WIDTH( 32 ),
    .din6_WIDTH( 32 ),
    .din7_WIDTH( 32 ),
    .din8_WIDTH( 32 ),
    .din9_WIDTH( 32 ),
    .din10_WIDTH( 4 ),
    .dout_WIDTH( 32 ))
mux_10_4_32_1_1_U77(
    .din0(32'd0),
    .din1(32'd0),
    .din2(32'd0),
    .din3(32'd0),
    .din4(32'd0),
    .din5(32'd0),
    .din6(32'd0),
    .din7(arg2_r_7_reload),
    .din8(arg2_r_8_reload),
    .din9(arg2_r_9_reload),
    .din10(tmp_3_fu_818_p11),
    .dout(tmp_3_fu_818_p12)
);

fiat_25519_carry_mul_mux_10_4_32_1_1 #(
    .ID( 1 ),
    .NUM_STAGE( 1 ),
    .din0_WIDTH( 32 ),
    .din1_WIDTH( 32 ),
    .din2_WIDTH( 32 ),
    .din3_WIDTH( 32 ),
    .din4_WIDTH( 32 ),
    .din5_WIDTH( 32 ),
    .din6_WIDTH( 32 ),
    .din7_WIDTH( 32 ),
    .din8_WIDTH( 32 ),
    .din9_WIDTH( 32 ),
    .din10_WIDTH( 4 ),
    .dout_WIDTH( 32 ))
mux_10_4_32_1_1_U78(
    .din0(32'd0),
    .din1(32'd0),
    .din2(32'd0),
    .din3(32'd0),
    .din4(32'd0),
    .din5(32'd0),
    .din6(arg2_r_6_reload),
    .din7(arg2_r_7_reload),
    .din8(arg2_r_8_reload),
    .din9(arg2_r_9_reload),
    .din10(tmp_4_fu_852_p11),
    .dout(tmp_4_fu_852_p12)
);

fiat_25519_carry_mul_mux_10_4_32_1_1 #(
    .ID( 1 ),
    .NUM_STAGE( 1 ),
    .din0_WIDTH( 32 ),
    .din1_WIDTH( 32 ),
    .din2_WIDTH( 32 ),
    .din3_WIDTH( 32 ),
    .din4_WIDTH( 32 ),
    .din5_WIDTH( 32 ),
    .din6_WIDTH( 32 ),
    .din7_WIDTH( 32 ),
    .din8_WIDTH( 32 ),
    .din9_WIDTH( 32 ),
    .din10_WIDTH( 4 ),
    .dout_WIDTH( 32 ))
mux_10_4_32_1_1_U79(
    .din0(32'd0),
    .din1(arg1_r_reload),
    .din2(arg1_r_1_reload),
    .din3(arg1_r_2_reload),
    .din4(arg1_r_3_reload),
    .din5(arg1_r_4_reload),
    .din6(arg1_r_5_reload),
    .din7(arg1_r_6_reload),
    .din8(arg1_r_7_reload),
    .din9(arg1_r_8_reload),
    .din10(trunc_ln39_fu_669_p1),
    .dout(tmp_5_fu_879_p12)
);

fiat_25519_carry_mul_mux_10_4_32_1_1 #(
    .ID( 1 ),
    .NUM_STAGE( 1 ),
    .din0_WIDTH( 32 ),
    .din1_WIDTH( 32 ),
    .din2_WIDTH( 32 ),
    .din3_WIDTH( 32 ),
    .din4_WIDTH( 32 ),
    .din5_WIDTH( 32 ),
    .din6_WIDTH( 32 ),
    .din7_WIDTH( 32 ),
    .din8_WIDTH( 32 ),
    .din9_WIDTH( 32 ),
    .din10_WIDTH( 4 ),
    .dout_WIDTH( 32 ))
mux_10_4_32_1_1_U80(
    .din0(32'd0),
    .din1(32'd0),
    .din2(32'd0),
    .din3(32'd0),
    .din4(32'd0),
    .din5(arg2_r_5_reload),
    .din6(arg2_r_6_reload),
    .din7(arg2_r_7_reload),
    .din8(arg2_r_8_reload),
    .din9(arg2_r_9_reload),
    .din10(tmp_6_fu_932_p11),
    .dout(tmp_6_fu_932_p12)
);

fiat_25519_carry_mul_mux_10_4_32_1_1 #(
    .ID( 1 ),
    .NUM_STAGE( 1 ),
    .din0_WIDTH( 32 ),
    .din1_WIDTH( 32 ),
    .din2_WIDTH( 32 ),
    .din3_WIDTH( 32 ),
    .din4_WIDTH( 32 ),
    .din5_WIDTH( 32 ),
    .din6_WIDTH( 32 ),
    .din7_WIDTH( 32 ),
    .din8_WIDTH( 32 ),
    .din9_WIDTH( 32 ),
    .din10_WIDTH( 4 ),
    .dout_WIDTH( 32 ))
mux_10_4_32_1_1_U81(
    .din0(32'd0),
    .din1(32'd0),
    .din2(32'd0),
    .din3(32'd0),
    .din4(arg2_r_4_reload),
    .din5(arg2_r_5_reload),
    .din6(arg2_r_6_reload),
    .din7(arg2_r_7_reload),
    .din8(arg2_r_8_reload),
    .din9(arg2_r_9_reload),
    .din10(tmp_7_fu_966_p11),
    .dout(tmp_7_fu_966_p12)
);

fiat_25519_carry_mul_mux_10_4_32_1_1 #(
    .ID( 1 ),
    .NUM_STAGE( 1 ),
    .din0_WIDTH( 32 ),
    .din1_WIDTH( 32 ),
    .din2_WIDTH( 32 ),
    .din3_WIDTH( 32 ),
    .din4_WIDTH( 32 ),
    .din5_WIDTH( 32 ),
    .din6_WIDTH( 32 ),
    .din7_WIDTH( 32 ),
    .din8_WIDTH( 32 ),
    .din9_WIDTH( 32 ),
    .din10_WIDTH( 4 ),
    .dout_WIDTH( 32 ))
mux_10_4_32_1_1_U82(
    .din0(32'd0),
    .din1(32'd0),
    .din2(32'd0),
    .din3(arg2_r_3_reload),
    .din4(arg2_r_4_reload),
    .din5(arg2_r_5_reload),
    .din6(arg2_r_6_reload),
    .din7(arg2_r_7_reload),
    .din8(arg2_r_8_reload),
    .din9(arg2_r_9_reload),
    .din10(tmp_8_fu_1020_p11),
    .dout(tmp_8_fu_1020_p12)
);

fiat_25519_carry_mul_mux_10_4_32_1_1 #(
    .ID( 1 ),
    .NUM_STAGE( 1 ),
    .din0_WIDTH( 32 ),
    .din1_WIDTH( 32 ),
    .din2_WIDTH( 32 ),
    .din3_WIDTH( 32 ),
    .din4_WIDTH( 32 ),
    .din5_WIDTH( 32 ),
    .din6_WIDTH( 32 ),
    .din7_WIDTH( 32 ),
    .din8_WIDTH( 32 ),
    .din9_WIDTH( 32 ),
    .din10_WIDTH( 4 ),
    .dout_WIDTH( 32 ))
mux_10_4_32_1_1_U83(
    .din0(32'd0),
    .din1(32'd0),
    .din2(arg2_r_2_reload),
    .din3(arg2_r_3_reload),
    .din4(arg2_r_4_reload),
    .din5(arg2_r_5_reload),
    .din6(arg2_r_6_reload),
    .din7(arg2_r_7_reload),
    .din8(arg2_r_8_reload),
    .din9(arg2_r_9_reload),
    .din10(tmp_9_fu_1054_p11),
    .dout(tmp_9_fu_1054_p12)
);

fiat_25519_carry_mul_mux_10_4_32_1_1 #(
    .ID( 1 ),
    .NUM_STAGE( 1 ),
    .din0_WIDTH( 32 ),
    .din1_WIDTH( 32 ),
    .din2_WIDTH( 32 ),
    .din3_WIDTH( 32 ),
    .din4_WIDTH( 32 ),
    .din5_WIDTH( 32 ),
    .din6_WIDTH( 32 ),
    .din7_WIDTH( 32 ),
    .din8_WIDTH( 32 ),
    .din9_WIDTH( 32 ),
    .din10_WIDTH( 4 ),
    .dout_WIDTH( 32 ))
mux_10_4_32_1_1_U84(
    .din0(32'd0),
    .din1(arg2_r_1_reload),
    .din2(arg2_r_2_reload),
    .din3(arg2_r_3_reload),
    .din4(arg2_r_4_reload),
    .din5(arg2_r_5_reload),
    .din6(arg2_r_6_reload),
    .din7(arg2_r_7_reload),
    .din8(arg2_r_8_reload),
    .din9(arg2_r_9_reload),
    .din10(tmp_s_fu_1087_p11),
    .dout(tmp_s_fu_1087_p12)
);

fiat_25519_carry_mul_mux_9_4_32_1_1 #(
    .ID( 1 ),
    .NUM_STAGE( 1 ),
    .din0_WIDTH( 32 ),
    .din1_WIDTH( 32 ),
    .din2_WIDTH( 32 ),
    .din3_WIDTH( 32 ),
    .din4_WIDTH( 32 ),
    .din5_WIDTH( 32 ),
    .din6_WIDTH( 32 ),
    .din7_WIDTH( 32 ),
    .din8_WIDTH( 32 ),
    .din9_WIDTH( 4 ),
    .dout_WIDTH( 32 ))
mux_9_4_32_1_1_U85(
    .din0(arg2_r_reload),
    .din1(arg2_r_1_reload),
    .din2(arg2_r_2_reload),
    .din3(arg2_r_3_reload),
    .din4(arg2_r_4_reload),
    .din5(arg2_r_5_reload),
    .din6(arg2_r_6_reload),
    .din7(arg2_r_7_reload),
    .din8(arg2_r_8_reload),
    .din9(sub_ln67_reg_2504),
    .dout(tmp_10_fu_1342_p11)
);

fiat_25519_carry_mul_mux_8_3_32_1_1 #(
    .ID( 1 ),
    .NUM_STAGE( 1 ),
    .din0_WIDTH( 32 ),
    .din1_WIDTH( 32 ),
    .din2_WIDTH( 32 ),
    .din3_WIDTH( 32 ),
    .din4_WIDTH( 32 ),
    .din5_WIDTH( 32 ),
    .din6_WIDTH( 32 ),
    .din7_WIDTH( 32 ),
    .din8_WIDTH( 3 ),
    .dout_WIDTH( 32 ))
mux_8_3_32_1_1_U86(
    .din0(arg2_r_reload),
    .din1(arg2_r_1_reload),
    .din2(arg2_r_2_reload),
    .din3(arg2_r_3_reload),
    .din4(arg2_r_4_reload),
    .din5(arg2_r_5_reload),
    .din6(arg2_r_6_reload),
    .din7(arg2_r_7_reload),
    .din8(sub_ln67_1_reg_2515),
    .dout(tmp_11_fu_1362_p10)
);

fiat_25519_carry_mul_mux_7_3_32_1_1 #(
    .ID( 1 ),
    .NUM_STAGE( 1 ),
    .din0_WIDTH( 32 ),
    .din1_WIDTH( 32 ),
    .din2_WIDTH( 32 ),
    .din3_WIDTH( 32 ),
    .din4_WIDTH( 32 ),
    .din5_WIDTH( 32 ),
    .din6_WIDTH( 32 ),
    .din7_WIDTH( 3 ),
    .dout_WIDTH( 32 ))
mux_7_3_32_1_1_U87(
    .din0(arg2_r_reload),
    .din1(arg2_r_1_reload),
    .din2(arg2_r_2_reload),
    .din3(arg2_r_3_reload),
    .din4(arg2_r_4_reload),
    .din5(arg2_r_5_reload),
    .din6(arg2_r_6_reload),
    .din7(tmp_12_fu_1398_p8),
    .dout(tmp_12_fu_1398_p9)
);

fiat_25519_carry_mul_mux_6_3_32_1_1 #(
    .ID( 1 ),
    .NUM_STAGE( 1 ),
    .din0_WIDTH( 32 ),
    .din1_WIDTH( 32 ),
    .din2_WIDTH( 32 ),
    .din3_WIDTH( 32 ),
    .din4_WIDTH( 32 ),
    .din5_WIDTH( 32 ),
    .din6_WIDTH( 3 ),
    .dout_WIDTH( 32 ))
mux_6_3_32_1_1_U88(
    .din0(arg2_r_reload),
    .din1(arg2_r_1_reload),
    .din2(arg2_r_2_reload),
    .din3(arg2_r_3_reload),
    .din4(arg2_r_4_reload),
    .din5(arg2_r_5_reload),
    .din6(sub_ln67_2_reg_2526),
    .dout(tmp_13_fu_1423_p8)
);

fiat_25519_carry_mul_mux_5_3_32_1_1 #(
    .ID( 1 ),
    .NUM_STAGE( 1 ),
    .din0_WIDTH( 32 ),
    .din1_WIDTH( 32 ),
    .din2_WIDTH( 32 ),
    .din3_WIDTH( 32 ),
    .din4_WIDTH( 32 ),
    .din5_WIDTH( 3 ),
    .dout_WIDTH( 32 ))
mux_5_3_32_1_1_U89(
    .din0(arg2_r_reload),
    .din1(arg2_r_1_reload),
    .din2(arg2_r_2_reload),
    .din3(arg2_r_3_reload),
    .din4(arg2_r_4_reload),
    .din5(tmp_14_fu_1457_p6),
    .dout(tmp_14_fu_1457_p7)
);

fiat_25519_carry_mul_mux_4_2_32_1_1 #(
    .ID( 1 ),
    .NUM_STAGE( 1 ),
    .din0_WIDTH( 32 ),
    .din1_WIDTH( 32 ),
    .din2_WIDTH( 32 ),
    .din3_WIDTH( 32 ),
    .din4_WIDTH( 2 ),
    .dout_WIDTH( 32 ))
mux_4_2_32_1_1_U90(
    .din0(arg2_r_reload),
    .din1(arg2_r_1_reload),
    .din2(arg2_r_2_reload),
    .din3(arg2_r_3_reload),
    .din4(tmp_15_fu_1746_p5),
    .dout(tmp_15_fu_1746_p6)
);

fiat_25519_carry_mul_mux_3_2_32_1_1 #(
    .ID( 1 ),
    .NUM_STAGE( 1 ),
    .din0_WIDTH( 32 ),
    .din1_WIDTH( 32 ),
    .din2_WIDTH( 32 ),
    .din3_WIDTH( 2 ),
    .dout_WIDTH( 32 ))
mux_3_2_32_1_1_U91(
    .din0(arg2_r_reload),
    .din1(arg2_r_1_reload),
    .din2(arg2_r_2_reload),
    .din3(tmp_16_fu_1780_p4),
    .dout(tmp_16_fu_1780_p5)
);

fiat_25519_carry_mul_flow_control_loop_pipe_sequential_init flow_control_loop_pipe_sequential_init_U(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst),
    .ap_start(ap_start),
    .ap_ready(ap_ready),
    .ap_done(ap_done),
    .ap_start_int(ap_start_int),
    .ap_loop_init(ap_loop_init),
    .ap_ready_int(ap_ready_int),
    .ap_loop_exit_ready(ap_condition_exit_pp0_iter0_stage0),
    .ap_loop_exit_done(ap_done_int),
    .ap_continue_int(ap_continue_int),
    .ap_done_int(ap_done_int)
);

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_CS_fsm <= ap_ST_fsm_pp0_stage0;
    end else begin
        ap_CS_fsm <= ap_NS_fsm;
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_done_reg <= 1'b0;
    end else begin
        if ((ap_continue_int == 1'b1)) begin
            ap_done_reg <= 1'b0;
        end else if (((ap_loop_exit_ready == 1'b1) & (1'b0 == ap_block_pp0_stage0_subdone) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
            ap_done_reg <= 1'b1;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter1 <= 1'b0;
    end else begin
        if ((1'b1 == ap_condition_exit_pp0_iter0_stage0)) begin
            ap_enable_reg_pp0_iter1 <= 1'b0;
        end else if (((1'b0 == ap_block_pp0_stage0_subdone) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
            ap_enable_reg_pp0_iter1 <= ap_start_int;
        end
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        if ((ap_loop_init == 1'b1)) begin
            add65220_fu_164 <= 64'd0;
        end else if ((ap_enable_reg_pp0_iter1 == 1'b1)) begin
            add65220_fu_164 <= add_ln67_1_fu_1490_p2;
        end
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        if ((ap_loop_init == 1'b1)) begin
            add65_1225_fu_184 <= 64'd0;
        end else if ((ap_enable_reg_pp0_iter1 == 1'b1)) begin
            add65_1225_fu_184 <= add_ln67_20_fu_1884_p2;
        end
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        if ((ap_loop_init == 1'b1)) begin
            add65_197221_fu_168 <= 64'd0;
        end else if ((ap_enable_reg_pp0_iter1 == 1'b1)) begin
            add65_197221_fu_168 <= add_ln67_4_fu_1534_p2;
        end
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        if ((ap_loop_init == 1'b1)) begin
            add65_1_132226_fu_188 <= 64'd0;
        end else if ((ap_enable_reg_pp0_iter1 == 1'b1)) begin
            add65_1_132226_fu_188 <= add_ln67_24_fu_1953_p2;
        end
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        if ((ap_loop_init == 1'b1)) begin
            add65_1_2227_fu_192 <= 64'd0;
        end else if ((ap_enable_reg_pp0_iter1 == 1'b1)) begin
            add65_1_2227_fu_192 <= add_ln67_28_fu_2015_p2;
        end
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        if ((ap_loop_init == 1'b1)) begin
            add65_1_3228_fu_196 <= 64'd0;
        end else if ((ap_enable_reg_pp0_iter1 == 1'b1)) begin
            add65_1_3228_fu_196 <= add_ln67_32_fu_2083_p2;
        end
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        if ((ap_loop_init == 1'b1)) begin
            add65_1_4229_fu_200 <= 64'd0;
        end else if ((ap_enable_reg_pp0_iter1 == 1'b1)) begin
            add65_1_4229_fu_200 <= add_ln67_35_fu_2113_p2;
        end
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        if ((ap_loop_init == 1'b1)) begin
            add65_2222_fu_172 <= 64'd0;
        end else if ((ap_enable_reg_pp0_iter1 == 1'b1)) begin
            add65_2222_fu_172 <= add_ln67_8_fu_1603_p2;
        end
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        if ((ap_loop_init == 1'b1)) begin
            add65_3223_fu_176 <= 64'd0;
        end else if ((ap_enable_reg_pp0_iter1 == 1'b1)) begin
            add65_3223_fu_176 <= add_ln67_12_fu_1665_p2;
        end
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        if ((ap_loop_init == 1'b1)) begin
            add65_4224_fu_180 <= 64'd0;
        end else if ((ap_enable_reg_pp0_iter1 == 1'b1)) begin
            add65_4224_fu_180 <= add_ln67_16_fu_1734_p2;
        end
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        if (((tmp_17_fu_661_p3 == 1'd0) & (ap_enable_reg_pp0_iter0 == 1'b1))) begin
            i1_fu_204 <= add_ln39_fu_1156_p2;
        end else if ((ap_loop_init == 1'b1)) begin
            i1_fu_204 <= 5'd9;
        end
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        i1_1_reg_2374 <= ap_sig_allocacmp_i1_1;
    end
end

always @ (posedge ap_clk) begin
    if (((tmp_17_fu_661_p3 == 1'd0) & (1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        icmp_ln51_1_reg_2424 <= icmp_ln51_1_fu_797_p2;
        icmp_ln51_2_reg_2454 <= icmp_ln51_2_fu_911_p2;
        icmp_ln51_3_reg_2469 <= icmp_ln51_3_fu_999_p2;
        icmp_ln51_reg_2397 <= icmp_ln51_fu_709_p2;
        icmp_ln66_1_reg_2520 <= icmp_ln66_1_fu_1132_p2;
        icmp_ln66_2_reg_2531 <= icmp_ln66_2_fu_1144_p2;
        icmp_ln66_3_reg_2537 <= icmp_ln66_3_fu_1150_p2;
        icmp_ln66_reg_2509 <= icmp_ln66_fu_1120_p2;
        mul_ln52_10_reg_2489 <= mul_ln52_10_fu_588_p2;
        mul_ln52_11_reg_2494 <= mul_ln52_11_fu_593_p2;
        mul_ln52_12_reg_2499 <= mul_ln52_12_fu_598_p2;
        mul_ln52_1_reg_2419 <= mul_ln52_1_fu_558_p2;
        mul_ln52_2_reg_2429 <= mul_ln52_2_fu_546_p2;
        mul_ln52_3_reg_2434 <= mul_ln52_3_fu_563_p2;
        mul_ln52_4_reg_2444 <= mul_ln52_4_fu_568_p2;
        mul_ln52_5_reg_2449 <= mul_ln52_5_fu_573_p2;
        mul_ln52_6_reg_2459 <= mul_ln52_6_fu_550_p2;
        mul_ln52_7_reg_2464 <= mul_ln52_7_fu_578_p2;
        mul_ln52_8_reg_2474 <= mul_ln52_8_fu_554_p2;
        mul_ln52_9_reg_2479 <= mul_ln52_9_fu_583_p2;
        mul_ln52_reg_2409 <= mul_ln52_fu_542_p2;
        sub_ln67_1_reg_2515 <= sub_ln67_1_fu_1126_p2;
        sub_ln67_2_reg_2526 <= sub_ln67_2_fu_1138_p2;
        sub_ln67_reg_2504 <= sub_ln67_fu_1114_p2;
        tmp_1_reg_2402 <= tmp_1_fu_730_p12;
        tmp_2_reg_2414 <= tmp_2_fu_764_p12;
        tmp_5_reg_2439 <= tmp_5_fu_879_p12;
        tmp_reg_2392 <= tmp_fu_677_p12;
        tmp_s_reg_2484 <= tmp_s_fu_1087_p12;
        trunc_ln39_2_reg_2386 <= trunc_ln39_2_fu_673_p1;
    end
end

always @ (*) begin
    if (((tmp_17_fu_661_p3 == 1'd1) & (1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        add65220_out_ap_vld = 1'b1;
    end else begin
        add65220_out_ap_vld = 1'b0;
    end
end

always @ (*) begin
    if (((tmp_17_fu_661_p3 == 1'd1) & (1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        add65_1225_out_ap_vld = 1'b1;
    end else begin
        add65_1225_out_ap_vld = 1'b0;
    end
end

always @ (*) begin
    if (((tmp_17_fu_661_p3 == 1'd1) & (1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        add65_197221_out_ap_vld = 1'b1;
    end else begin
        add65_197221_out_ap_vld = 1'b0;
    end
end

always @ (*) begin
    if (((tmp_17_fu_661_p3 == 1'd1) & (1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        add65_1_132226_out_ap_vld = 1'b1;
    end else begin
        add65_1_132226_out_ap_vld = 1'b0;
    end
end

always @ (*) begin
    if (((tmp_17_fu_661_p3 == 1'd1) & (1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        add65_1_2227_out_ap_vld = 1'b1;
    end else begin
        add65_1_2227_out_ap_vld = 1'b0;
    end
end

always @ (*) begin
    if (((tmp_17_fu_661_p3 == 1'd1) & (1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        add65_1_3228_out_ap_vld = 1'b1;
    end else begin
        add65_1_3228_out_ap_vld = 1'b0;
    end
end

always @ (*) begin
    if (((tmp_17_fu_661_p3 == 1'd1) & (1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        add65_1_4229_out_ap_vld = 1'b1;
    end else begin
        add65_1_4229_out_ap_vld = 1'b0;
    end
end

always @ (*) begin
    if (((tmp_17_fu_661_p3 == 1'd1) & (1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        add65_2222_out_ap_vld = 1'b1;
    end else begin
        add65_2222_out_ap_vld = 1'b0;
    end
end

always @ (*) begin
    if (((tmp_17_fu_661_p3 == 1'd1) & (1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        add65_3223_out_ap_vld = 1'b1;
    end else begin
        add65_3223_out_ap_vld = 1'b0;
    end
end

always @ (*) begin
    if (((tmp_17_fu_661_p3 == 1'd1) & (1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        add65_4224_out_ap_vld = 1'b1;
    end else begin
        add65_4224_out_ap_vld = 1'b0;
    end
end

always @ (*) begin
    if (((tmp_17_fu_661_p3 == 1'd1) & (1'b0 == ap_block_pp0_stage0_subdone) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        ap_condition_exit_pp0_iter0_stage0 = 1'b1;
    end else begin
        ap_condition_exit_pp0_iter0_stage0 = 1'b0;
    end
end

always @ (*) begin
    if (((ap_loop_exit_ready == 1'b1) & (1'b0 == ap_block_pp0_stage0_subdone) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        ap_done_int = 1'b1;
    end else begin
        ap_done_int = ap_done_reg;
    end
end

always @ (*) begin
    if (((ap_idle_pp0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0) & (ap_start_int == 1'b0))) begin
        ap_idle = 1'b1;
    end else begin
        ap_idle = 1'b0;
    end
end

always @ (*) begin
    if (((ap_enable_reg_pp0_iter1 == 1'b0) & (ap_enable_reg_pp0_iter0 == 1'b0))) begin
        ap_idle_pp0 = 1'b1;
    end else begin
        ap_idle_pp0 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_subdone) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        ap_ready_int = 1'b1;
    end else begin
        ap_ready_int = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0) & (1'b1 == ap_CS_fsm_pp0_stage0) & (ap_loop_init == 1'b1))) begin
        ap_sig_allocacmp_i1_1 = 5'd9;
    end else begin
        ap_sig_allocacmp_i1_1 = i1_fu_204;
    end
end

always @ (*) begin
    case (ap_CS_fsm)
        ap_ST_fsm_pp0_stage0 : begin
            ap_NS_fsm = ap_ST_fsm_pp0_stage0;
        end
        default : begin
            ap_NS_fsm = 'bx;
        end
    endcase
end

assign add65220_out = add65220_fu_164;

assign add65_1225_out = add65_1225_fu_184;

assign add65_197221_out = add65_197221_fu_168;

assign add65_1_132226_out = add65_1_132226_fu_188;

assign add65_1_2227_out = add65_1_2227_fu_192;

assign add65_1_3228_out = add65_1_3228_fu_196;

assign add65_1_4229_out = add65_1_4229_fu_200;

assign add65_2222_out = add65_2222_fu_172;

assign add65_3223_out = add65_3223_fu_176;

assign add65_4224_out = add65_4224_fu_180;

assign add_ln39_fu_1156_p2 = ($signed(ap_sig_allocacmp_i1_1) + $signed(5'd30));

assign add_ln51_1_fu_791_p2 = (ap_sig_allocacmp_i1_1 + 5'd3);

assign add_ln51_2_fu_993_p2 = (ap_sig_allocacmp_i1_1 + 5'd7);

assign add_ln51_fu_703_p2 = (ap_sig_allocacmp_i1_1 + 5'd1);

assign add_ln52_1_fu_1245_p2 = (i1_1_reg_2374 + 5'd4);

assign add_ln52_2_fu_1294_p2 = (i1_1_reg_2374 + 5'd6);

assign add_ln52_3_fu_1314_p2 = (i1_1_reg_2374 + 5'd8);

assign add_ln52_fu_1225_p2 = (i1_1_reg_2374 + 5'd2);

assign add_ln67_10_fu_1653_p2 = (and_ln67_6_fu_1609_p2 + and_ln67_8_fu_1628_p2);

assign add_ln67_11_fu_1659_p2 = (add_ln67_10_fu_1653_p2 + add_ln67_9_fu_1647_p2);

assign add_ln67_12_fu_1665_p2 = (add65_3223_fu_176 + add_ln67_11_fu_1659_p2);

assign add_ln67_13_fu_1716_p2 = (and_ln67_11_fu_1682_p2 + and_ln67_13_fu_1710_p2);

assign add_ln67_14_fu_1722_p2 = (and_ln67_10_fu_1676_p2 + and_ln67_12_fu_1696_p2);

assign add_ln67_15_fu_1728_p2 = (add_ln67_14_fu_1722_p2 + add_ln67_13_fu_1716_p2);

assign add_ln67_16_fu_1734_p2 = (add65_4224_fu_180 + add_ln67_15_fu_1728_p2);

assign add_ln67_17_fu_1866_p2 = (and_ln67_15_fu_1834_p2 + and_ln67_17_fu_1860_p2);

assign add_ln67_18_fu_1872_p2 = (and_ln67_14_fu_1828_p2 + and_ln67_16_fu_1847_p2);

assign add_ln67_19_fu_1878_p2 = (add_ln67_18_fu_1872_p2 + add_ln67_17_fu_1866_p2);

assign add_ln67_1_fu_1490_p2 = (add65220_fu_164 + add_ln67_fu_1484_p2);

assign add_ln67_20_fu_1884_p2 = (add65_1225_fu_184 + add_ln67_19_fu_1878_p2);

assign add_ln67_21_fu_1935_p2 = (and_ln67_19_fu_1901_p2 + and_ln67_21_fu_1929_p2);

assign add_ln67_22_fu_1941_p2 = (and_ln67_18_fu_1895_p2 + and_ln67_20_fu_1915_p2);

assign add_ln67_23_fu_1947_p2 = (add_ln67_22_fu_1941_p2 + add_ln67_21_fu_1935_p2);

assign add_ln67_24_fu_1953_p2 = (add65_1_132226_fu_188 + add_ln67_23_fu_1947_p2);

assign add_ln67_25_fu_1997_p2 = (and_ln67_24_fu_1978_p2 + and_ln67_23_fu_1965_p2);

assign add_ln67_26_fu_2003_p2 = (and_ln67_25_fu_1991_p2 + and_ln67_22_fu_1959_p2);

assign add_ln67_27_fu_2009_p2 = (add_ln67_26_fu_2003_p2 + add_ln67_25_fu_1997_p2);

assign add_ln67_28_fu_2015_p2 = (add65_1_2227_fu_192 + add_ln67_27_fu_2009_p2);

assign add_ln67_29_fu_2065_p2 = (and_ln67_28_fu_2045_p2 + and_ln67_26_fu_2025_p2);

assign add_ln67_2_fu_1522_p2 = (mul_ln67_4_fu_414_p2 + and_ln67_1_fu_1516_p2);

assign add_ln67_30_fu_2071_p2 = (and_ln67_27_fu_2031_p2 + and_ln67_29_fu_2059_p2);

assign add_ln67_31_fu_2077_p2 = (add_ln67_30_fu_2071_p2 + add_ln67_29_fu_2065_p2);

assign add_ln67_32_fu_2083_p2 = (add65_1_3228_fu_196 + add_ln67_31_fu_2077_p2);

assign add_ln67_33_fu_2101_p2 = (and_ln67_31_fu_2095_p2 + mul_ln67_35_fu_538_p2);

assign add_ln67_34_fu_2107_p2 = (add_ln67_33_fu_2101_p2 + and_ln67_30_fu_2089_p2);

assign add_ln67_35_fu_2113_p2 = (add65_1_4229_fu_200 + add_ln67_34_fu_2107_p2);

assign add_ln67_3_fu_1528_p2 = (add_ln67_2_fu_1522_p2 + and_ln67_fu_1503_p2);

assign add_ln67_4_fu_1534_p2 = (add65_197221_fu_168 + add_ln67_3_fu_1528_p2);

assign add_ln67_5_fu_1585_p2 = (and_ln67_5_fu_1579_p2 + and_ln67_3_fu_1551_p2);

assign add_ln67_6_fu_1591_p2 = (and_ln67_2_fu_1545_p2 + and_ln67_4_fu_1565_p2);

assign add_ln67_7_fu_1597_p2 = (add_ln67_6_fu_1591_p2 + add_ln67_5_fu_1585_p2);

assign add_ln67_8_fu_1603_p2 = (add65_2222_fu_172 + add_ln67_7_fu_1597_p2);

assign add_ln67_9_fu_1647_p2 = (and_ln67_9_fu_1641_p2 + and_ln67_7_fu_1615_p2);

assign add_ln67_fu_1484_p2 = (mul_ln67_fu_398_p2 + mul_ln67_1_fu_402_p2);

assign and_ln67_10_fu_1676_p2 = (select_ln67_8_fu_1621_p3 & mul_ln67_13_fu_450_p2);

assign and_ln67_11_fu_1682_p2 = (select_ln67_9_fu_1634_p3 & mul_ln67_14_fu_454_p2);

assign and_ln67_12_fu_1696_p2 = (select_ln67_10_fu_1688_p3 & mul_ln67_15_fu_458_p2);

assign and_ln67_13_fu_1710_p2 = (select_ln67_11_fu_1702_p3 & mul_ln67_16_fu_462_p2);

assign and_ln67_14_fu_1828_p2 = (select_ln67_10_fu_1688_p3 & mul_ln67_17_fu_466_p2);

assign and_ln67_15_fu_1834_p2 = (select_ln67_11_fu_1702_p3 & mul_ln67_18_fu_470_p2);

assign and_ln67_16_fu_1847_p2 = (select_ln67_12_fu_1840_p3 & mul_ln67_19_fu_474_p2);

assign and_ln67_17_fu_1860_p2 = (select_ln67_13_fu_1853_p3 & mul_ln67_20_fu_478_p2);

assign and_ln67_18_fu_1895_p2 = (select_ln67_12_fu_1840_p3 & mul_ln67_21_fu_482_p2);

assign and_ln67_19_fu_1901_p2 = (select_ln67_13_fu_1853_p3 & mul_ln67_22_fu_486_p2);

assign and_ln67_1_fu_1516_p2 = (select_ln67_5_fu_1509_p3 & mul_ln67_3_fu_410_p2);

assign and_ln67_20_fu_1915_p2 = (select_ln67_14_fu_1907_p3 & mul_ln67_23_fu_490_p2);

assign and_ln67_21_fu_1929_p2 = (select_ln67_15_fu_1921_p3 & mul_ln67_24_fu_494_p2);

assign and_ln67_22_fu_1959_p2 = (select_ln67_14_fu_1907_p3 & mul_ln67_25_fu_498_p2);

assign and_ln67_23_fu_1965_p2 = (select_ln67_15_fu_1921_p3 & mul_ln67_26_fu_502_p2);

assign and_ln67_24_fu_1978_p2 = (select_ln67_16_fu_1971_p3 & mul_ln67_27_fu_506_p2);

assign and_ln67_25_fu_1991_p2 = (select_ln67_17_fu_1984_p3 & mul_ln67_28_fu_510_p2);

assign and_ln67_26_fu_2025_p2 = (select_ln67_16_fu_1971_p3 & mul_ln67_29_fu_514_p2);

assign and_ln67_27_fu_2031_p2 = (select_ln67_17_fu_1984_p3 & mul_ln67_30_fu_518_p2);

assign and_ln67_28_fu_2045_p2 = (select_ln67_18_fu_2037_p3 & mul_ln67_31_fu_522_p2);

assign and_ln67_29_fu_2059_p2 = (select_ln67_19_fu_2051_p3 & mul_ln67_32_fu_526_p2);

assign and_ln67_2_fu_1545_p2 = (select_ln67_5_fu_1509_p3 & mul_ln67_5_fu_418_p2);

assign and_ln67_30_fu_2089_p2 = (select_ln67_18_fu_2037_p3 & mul_ln67_33_fu_530_p2);

assign and_ln67_31_fu_2095_p2 = (select_ln67_19_fu_2051_p3 & mul_ln67_34_fu_534_p2);

assign and_ln67_3_fu_1551_p2 = (select_ln67_4_fu_1496_p3 & mul_ln67_6_fu_422_p2);

assign and_ln67_4_fu_1565_p2 = (select_ln67_6_fu_1557_p3 & mul_ln67_7_fu_426_p2);

assign and_ln67_5_fu_1579_p2 = (select_ln67_7_fu_1571_p3 & mul_ln67_8_fu_430_p2);

assign and_ln67_6_fu_1609_p2 = (select_ln67_6_fu_1557_p3 & mul_ln67_9_fu_434_p2);

assign and_ln67_7_fu_1615_p2 = (select_ln67_7_fu_1571_p3 & mul_ln67_10_fu_438_p2);

assign and_ln67_8_fu_1628_p2 = (select_ln67_8_fu_1621_p3 & mul_ln67_11_fu_442_p2);

assign and_ln67_9_fu_1641_p2 = (select_ln67_9_fu_1634_p3 & mul_ln67_12_fu_446_p2);

assign and_ln67_fu_1503_p2 = (select_ln67_4_fu_1496_p3 & mul_ln67_2_fu_406_p2);

assign ap_CS_fsm_pp0_stage0 = ap_CS_fsm[32'd0];

assign ap_block_pp0_stage0 = ~(1'b1 == 1'b1);

assign ap_block_pp0_stage0_01001 = ~(1'b1 == 1'b1);

assign ap_block_pp0_stage0_11001 = ~(1'b1 == 1'b1);

assign ap_block_pp0_stage0_subdone = ~(1'b1 == 1'b1);

assign ap_block_state1_pp0_stage0_iter0 = ~(1'b1 == 1'b1);

assign ap_block_state2_pp0_stage0_iter1 = ~(1'b1 == 1'b1);

assign ap_enable_pp0 = (ap_idle_pp0 ^ 1'b1);

assign ap_enable_reg_pp0_iter0 = ap_start_int;

assign ap_loop_exit_ready = ap_condition_exit_pp0_iter0_stage0;

assign empty_fu_905_p2 = (ap_sig_allocacmp_i1_1 + 5'd5);

assign icmp_ln51_1_fu_797_p2 = (($signed(add_ln51_1_fu_791_p2) > $signed(5'd9)) ? 1'b1 : 1'b0);

assign icmp_ln51_2_fu_911_p2 = (($signed(empty_fu_905_p2) > $signed(5'd9)) ? 1'b1 : 1'b0);

assign icmp_ln51_3_fu_999_p2 = ((add_ln51_2_fu_993_p2 > 5'd9) ? 1'b1 : 1'b0);

assign icmp_ln51_fu_709_p2 = (($signed(add_ln51_fu_703_p2) > $signed(5'd9)) ? 1'b1 : 1'b0);

assign icmp_ln52_1_fu_1255_p2 = (($signed(add_ln52_1_fu_1245_p2) > $signed(5'd9)) ? 1'b1 : 1'b0);

assign icmp_ln52_2_fu_1304_p2 = (($signed(add_ln52_2_fu_1294_p2) > $signed(5'd9)) ? 1'b1 : 1'b0);

assign icmp_ln52_3_fu_1324_p2 = ((add_ln52_3_fu_1314_p2 > 5'd9) ? 1'b1 : 1'b0);

assign icmp_ln52_fu_1235_p2 = (($signed(add_ln52_fu_1225_p2) > $signed(5'd9)) ? 1'b1 : 1'b0);

assign icmp_ln66_1_fu_1132_p2 = (($signed(add_ln51_1_fu_791_p2) < $signed(5'd10)) ? 1'b1 : 1'b0);

assign icmp_ln66_2_fu_1144_p2 = (($signed(empty_fu_905_p2) < $signed(5'd10)) ? 1'b1 : 1'b0);

assign icmp_ln66_3_fu_1150_p2 = ((add_ln51_2_fu_993_p2 < 5'd10) ? 1'b1 : 1'b0);

assign icmp_ln66_fu_1120_p2 = (($signed(add_ln51_fu_703_p2) < $signed(5'd10)) ? 1'b1 : 1'b0);

assign icmp_ln67_1_fu_1474_p2 = (($signed(add_ln52_1_fu_1245_p2) < $signed(5'd10)) ? 1'b1 : 1'b0);

assign icmp_ln67_2_fu_1795_p2 = (($signed(add_ln52_2_fu_1294_p2) < $signed(5'd10)) ? 1'b1 : 1'b0);

assign icmp_ln67_3_fu_1822_p2 = ((add_ln52_3_fu_1314_p2 < 5'd10) ? 1'b1 : 1'b0);

assign icmp_ln67_fu_1417_p2 = (($signed(add_ln52_fu_1225_p2) < $signed(5'd10)) ? 1'b1 : 1'b0);

assign mul_ln52_10_fu_588_p1 = 32'd38;

assign mul_ln52_11_fu_593_p1 = 32'd19;

assign mul_ln52_12_fu_598_p1 = 32'd19;

assign mul_ln52_1_fu_558_p1 = 32'd19;

assign mul_ln52_2_fu_546_p1 = mul_ln52_2_fu_546_p10;

assign mul_ln52_2_fu_546_p10 = ((icmp_ln51_1_fu_797_p2[0:0] == 1'b1) ? 32'd38 : 32'd19);

assign mul_ln52_3_fu_563_p1 = 32'd19;

assign mul_ln52_4_fu_568_p1 = 32'd19;

assign mul_ln52_5_fu_573_p1 = 32'd19;

assign mul_ln52_6_fu_550_p1 = mul_ln52_6_fu_550_p10;

assign mul_ln52_6_fu_550_p10 = ((icmp_ln51_2_fu_911_p2[0:0] == 1'b1) ? 32'd38 : 32'd19);

assign mul_ln52_7_fu_578_p1 = 32'd19;

assign mul_ln52_8_fu_554_p1 = mul_ln52_8_fu_554_p10;

assign mul_ln52_8_fu_554_p10 = ((icmp_ln51_3_fu_999_p2[0:0] == 1'b1) ? 32'd38 : 32'd19);

assign mul_ln52_9_fu_583_p1 = 32'd19;

assign mul_ln52_fu_542_p1 = mul_ln52_fu_542_p10;

assign mul_ln52_fu_542_p10 = ((icmp_ln51_fu_709_p2[0:0] == 1'b1) ? 32'd38 : 32'd19);

assign mul_ln67_10_fu_438_p0 = zext_ln52_5_fu_1261_p1;

assign mul_ln67_10_fu_438_p1 = zext_ln52_2_fu_1230_p1;

assign mul_ln67_11_fu_442_p0 = mul_ln67_11_fu_442_p00;

assign mul_ln67_11_fu_442_p00 = select_ln67_1_fu_1440_p3;

assign mul_ln67_11_fu_442_p1 = zext_ln52_fu_1200_p1;

assign mul_ln67_12_fu_446_p0 = mul_ln67_12_fu_446_p00;

assign mul_ln67_12_fu_446_p00 = mul_ln52_2_reg_2429;

assign mul_ln67_12_fu_446_p1 = zext_ln52_fu_1200_p1;

assign mul_ln67_13_fu_450_p0 = mul_ln67_13_fu_450_p00;

assign mul_ln67_13_fu_450_p00 = tmp_13_fu_1423_p8;

assign mul_ln67_13_fu_450_p1 = zext_ln52_5_fu_1261_p1;

assign mul_ln67_14_fu_454_p0 = zext_ln52_5_fu_1261_p1;

assign mul_ln67_14_fu_454_p1 = mul_ln67_14_fu_454_p10;

assign mul_ln67_14_fu_454_p10 = mul_ln52_5_reg_2449;

assign mul_ln67_15_fu_458_p0 = zext_ln67_4_fu_1468_p1;

assign mul_ln67_15_fu_458_p1 = zext_ln52_fu_1200_p1;

assign mul_ln67_16_fu_462_p0 = zext_ln52_4_fu_1250_p1;

assign mul_ln67_16_fu_462_p1 = zext_ln52_fu_1200_p1;

assign mul_ln67_17_fu_466_p0 = zext_ln67_4_fu_1468_p1;

assign mul_ln67_17_fu_466_p1 = zext_ln52_5_fu_1261_p1;

assign mul_ln67_18_fu_470_p0 = zext_ln52_4_fu_1250_p1;

assign mul_ln67_18_fu_470_p1 = zext_ln52_5_fu_1261_p1;

assign mul_ln67_19_fu_474_p0 = mul_ln67_19_fu_474_p00;

assign mul_ln67_19_fu_474_p00 = select_ln67_2_fu_1762_p3;

assign mul_ln67_19_fu_474_p1 = zext_ln52_fu_1200_p1;

assign mul_ln67_1_fu_402_p0 = mul_ln67_1_fu_402_p00;

assign mul_ln67_1_fu_402_p00 = $unsigned(tmp_s_reg_2484);

assign mul_ln67_1_fu_402_p1 = zext_ln52_5_fu_1261_p1;

assign mul_ln67_20_fu_478_p0 = mul_ln67_20_fu_478_p00;

assign mul_ln67_20_fu_478_p00 = mul_ln52_6_reg_2459;

assign mul_ln67_20_fu_478_p1 = zext_ln52_fu_1200_p1;

assign mul_ln67_21_fu_482_p0 = mul_ln67_21_fu_482_p00;

assign mul_ln67_21_fu_482_p00 = tmp_15_fu_1746_p6;

assign mul_ln67_21_fu_482_p1 = zext_ln52_5_fu_1261_p1;

assign mul_ln67_22_fu_486_p0 = mul_ln67_22_fu_486_p00;

assign mul_ln67_22_fu_486_p00 = mul_ln52_11_reg_2494;

assign mul_ln67_22_fu_486_p1 = zext_ln52_5_fu_1261_p1;

assign mul_ln67_23_fu_490_p0 = zext_ln67_9_fu_1789_p1;

assign mul_ln67_23_fu_490_p1 = zext_ln52_fu_1200_p1;

assign mul_ln67_24_fu_494_p0 = zext_ln52_9_fu_1299_p1;

assign mul_ln67_24_fu_494_p1 = zext_ln52_fu_1200_p1;

assign mul_ln67_25_fu_498_p0 = zext_ln67_9_fu_1789_p1;

assign mul_ln67_25_fu_498_p1 = zext_ln52_5_fu_1261_p1;

assign mul_ln67_26_fu_502_p0 = zext_ln52_9_fu_1299_p1;

assign mul_ln67_26_fu_502_p1 = zext_ln52_5_fu_1261_p1;

assign mul_ln67_27_fu_506_p0 = mul_ln67_27_fu_506_p00;

assign mul_ln67_27_fu_506_p00 = select_ln67_3_fu_1806_p3;

assign mul_ln67_27_fu_506_p1 = zext_ln52_fu_1200_p1;

assign mul_ln67_28_fu_510_p0 = mul_ln67_28_fu_510_p00;

assign mul_ln67_28_fu_510_p00 = mul_ln52_8_reg_2474;

assign mul_ln67_28_fu_510_p1 = zext_ln52_fu_1200_p1;

assign mul_ln67_29_fu_514_p0 = zext_ln52_5_fu_1261_p1;

assign mul_ln67_29_fu_514_p1 = mul_ln67_29_fu_514_p10;

assign mul_ln67_29_fu_514_p10 = $unsigned(tmp_1_reg_2402);

assign mul_ln67_2_fu_406_p0 = mul_ln67_2_fu_406_p00;

assign mul_ln67_2_fu_406_p00 = mul_ln52_reg_2409;

assign mul_ln67_2_fu_406_p1 = zext_ln52_fu_1200_p1;

assign mul_ln67_30_fu_518_p0 = mul_ln67_30_fu_518_p00;

assign mul_ln67_30_fu_518_p00 = mul_ln52_12_reg_2499;

assign mul_ln67_30_fu_518_p1 = zext_ln52_5_fu_1261_p1;

assign mul_ln67_31_fu_522_p0 = zext_ln67_11_fu_1817_p1;

assign mul_ln67_31_fu_522_p1 = zext_ln52_fu_1200_p1;

assign mul_ln67_32_fu_526_p0 = zext_ln52_11_fu_1319_p1;

assign mul_ln67_32_fu_526_p1 = zext_ln52_fu_1200_p1;

assign mul_ln67_33_fu_530_p0 = zext_ln52_5_fu_1261_p1;

assign mul_ln67_33_fu_530_p1 = zext_ln67_11_fu_1817_p1;

assign mul_ln67_34_fu_534_p0 = zext_ln52_11_fu_1319_p1;

assign mul_ln67_34_fu_534_p1 = zext_ln52_5_fu_1261_p1;

assign mul_ln67_35_fu_538_p0 = mul_ln67_35_fu_538_p00;

assign mul_ln67_35_fu_538_p00 = mul_ln52_10_reg_2489;

assign mul_ln67_35_fu_538_p1 = zext_ln52_fu_1200_p1;

assign mul_ln67_3_fu_410_p0 = mul_ln67_3_fu_410_p00;

assign mul_ln67_3_fu_410_p00 = select_ln67_fu_1381_p3;

assign mul_ln67_3_fu_410_p1 = zext_ln52_fu_1200_p1;

assign mul_ln67_4_fu_414_p0 = zext_ln67_fu_1356_p1;

assign mul_ln67_4_fu_414_p1 = zext_ln52_5_fu_1261_p1;

assign mul_ln67_5_fu_418_p0 = mul_ln67_5_fu_418_p00;

assign mul_ln67_5_fu_418_p00 = tmp_11_fu_1362_p10;

assign mul_ln67_5_fu_418_p1 = zext_ln52_5_fu_1261_p1;

assign mul_ln67_6_fu_422_p0 = zext_ln52_5_fu_1261_p1;

assign mul_ln67_6_fu_422_p1 = mul_ln67_6_fu_422_p10;

assign mul_ln67_6_fu_422_p10 = mul_ln52_4_reg_2444;

assign mul_ln67_7_fu_426_p0 = zext_ln67_2_fu_1411_p1;

assign mul_ln67_7_fu_426_p1 = zext_ln52_fu_1200_p1;

assign mul_ln67_8_fu_430_p0 = zext_ln52_2_fu_1230_p1;

assign mul_ln67_8_fu_430_p1 = zext_ln52_fu_1200_p1;

assign mul_ln67_9_fu_434_p0 = zext_ln67_2_fu_1411_p1;

assign mul_ln67_9_fu_434_p1 = zext_ln52_5_fu_1261_p1;

assign mul_ln67_fu_398_p0 = zext_ln67_fu_1356_p1;

assign mul_ln67_fu_398_p1 = zext_ln52_fu_1200_p1;

assign select_ln67_10_fu_1688_p3 = ((icmp_ln67_1_fu_1474_p2[0:0] == 1'b1) ? 64'd18446744073709551615 : 64'd0);

assign select_ln67_11_fu_1702_p3 = ((icmp_ln52_1_fu_1255_p2[0:0] == 1'b1) ? 64'd18446744073709551615 : 64'd0);

assign select_ln67_12_fu_1840_p3 = ((icmp_ln66_2_reg_2531[0:0] == 1'b1) ? 64'd18446744073709551615 : 64'd0);

assign select_ln67_13_fu_1853_p3 = ((icmp_ln51_2_reg_2454[0:0] == 1'b1) ? 64'd18446744073709551615 : 64'd0);

assign select_ln67_14_fu_1907_p3 = ((icmp_ln67_2_fu_1795_p2[0:0] == 1'b1) ? 64'd18446744073709551615 : 64'd0);

assign select_ln67_15_fu_1921_p3 = ((icmp_ln52_2_fu_1304_p2[0:0] == 1'b1) ? 64'd18446744073709551615 : 64'd0);

assign select_ln67_16_fu_1971_p3 = ((icmp_ln66_3_reg_2537[0:0] == 1'b1) ? 64'd18446744073709551615 : 64'd0);

assign select_ln67_17_fu_1984_p3 = ((icmp_ln51_3_reg_2469[0:0] == 1'b1) ? 64'd18446744073709551615 : 64'd0);

assign select_ln67_18_fu_2037_p3 = ((icmp_ln67_3_fu_1822_p2[0:0] == 1'b1) ? 64'd18446744073709551615 : 64'd0);

assign select_ln67_19_fu_2051_p3 = ((icmp_ln52_3_fu_1324_p2[0:0] == 1'b1) ? 64'd18446744073709551615 : 64'd0);

assign select_ln67_1_fu_1440_p3 = ((icmp_ln66_1_reg_2520[0:0] == 1'b1) ? shl_ln67_1_fu_1434_p2 : tmp_13_fu_1423_p8);

assign select_ln67_2_fu_1762_p3 = ((icmp_ln66_2_reg_2531[0:0] == 1'b1) ? shl_ln67_2_fu_1756_p2 : tmp_15_fu_1746_p6);

assign select_ln67_3_fu_1806_p3 = ((icmp_ln66_3_reg_2537[0:0] == 1'b1) ? shl_ln67_3_fu_1801_p2 : tmp_1_reg_2402);

assign select_ln67_4_fu_1496_p3 = ((icmp_ln51_reg_2397[0:0] == 1'b1) ? 64'd18446744073709551615 : 64'd0);

assign select_ln67_5_fu_1509_p3 = ((icmp_ln66_reg_2509[0:0] == 1'b1) ? 64'd18446744073709551615 : 64'd0);

assign select_ln67_6_fu_1557_p3 = ((icmp_ln67_fu_1417_p2[0:0] == 1'b1) ? 64'd18446744073709551615 : 64'd0);

assign select_ln67_7_fu_1571_p3 = ((icmp_ln52_fu_1235_p2[0:0] == 1'b1) ? 64'd18446744073709551615 : 64'd0);

assign select_ln67_8_fu_1621_p3 = ((icmp_ln66_1_reg_2520[0:0] == 1'b1) ? 64'd18446744073709551615 : 64'd0);

assign select_ln67_9_fu_1634_p3 = ((icmp_ln51_1_reg_2424[0:0] == 1'b1) ? 64'd18446744073709551615 : 64'd0);

assign select_ln67_fu_1381_p3 = ((icmp_ln66_reg_2509[0:0] == 1'b1) ? shl_ln67_fu_1375_p2 : tmp_11_fu_1362_p10);

assign shl_ln67_1_fu_1434_p2 = tmp_13_fu_1423_p8 << 32'd1;

assign shl_ln67_2_fu_1756_p2 = tmp_15_fu_1746_p6 << 32'd1;

assign shl_ln67_3_fu_1801_p2 = tmp_1_reg_2402 << 32'd1;

assign shl_ln67_fu_1375_p2 = tmp_11_fu_1362_p10 << 32'd1;

assign sub_ln67_1_fu_1126_p2 = (3'd0 - trunc_ln39_2_fu_673_p1);

assign sub_ln67_2_fu_1138_p2 = ($signed(3'd6) - $signed(trunc_ln39_2_fu_673_p1));

assign sub_ln67_fu_1114_p2 = ($signed(4'd9) - $signed(trunc_ln39_fu_669_p1));

assign tmp_12_fu_1398_p8 = (trunc_ln39_2_reg_2386 ^ 3'd7);

assign tmp_14_fu_1457_p6 = ($signed(3'd5) - $signed(trunc_ln39_2_reg_2386));

assign tmp_15_fu_1746_p5 = (2'd0 - trunc_ln39_1_fu_1197_p1);

assign tmp_16_fu_1780_p4 = (trunc_ln39_1_fu_1197_p1 ^ 2'd3);

assign tmp_17_fu_661_p3 = ap_sig_allocacmp_i1_1[32'd4];

assign tmp_1_fu_730_p11 = (4'd2 - trunc_ln39_fu_669_p1);

assign tmp_2_fu_764_p11 = (4'd1 - trunc_ln39_fu_669_p1);

assign tmp_3_fu_818_p11 = (4'd0 - trunc_ln39_fu_669_p1);

assign tmp_4_fu_852_p11 = (trunc_ln39_fu_669_p1 ^ 4'd15);

assign tmp_6_fu_932_p11 = ($signed(4'd14) - $signed(trunc_ln39_fu_669_p1));

assign tmp_7_fu_966_p11 = ($signed(4'd13) - $signed(trunc_ln39_fu_669_p1));

assign tmp_8_fu_1020_p11 = ($signed(4'd12) - $signed(trunc_ln39_fu_669_p1));

assign tmp_9_fu_1054_p11 = ($signed(4'd11) - $signed(trunc_ln39_fu_669_p1));

assign tmp_s_fu_1087_p11 = ($signed(4'd10) - $signed(trunc_ln39_fu_669_p1));

assign trunc_ln39_1_fu_1197_p1 = i1_1_reg_2374[1:0];

assign trunc_ln39_2_fu_673_p1 = ap_sig_allocacmp_i1_1[2:0];

assign trunc_ln39_fu_669_p1 = ap_sig_allocacmp_i1_1[3:0];

assign zext_ln52_11_fu_1319_p1 = mul_ln52_9_reg_2479;

assign zext_ln52_2_fu_1230_p1 = mul_ln52_1_reg_2419;

assign zext_ln52_4_fu_1250_p1 = mul_ln52_3_reg_2434;

assign zext_ln52_5_fu_1261_p1 = tmp_5_reg_2439;

assign zext_ln52_9_fu_1299_p1 = mul_ln52_7_reg_2464;

assign zext_ln52_fu_1200_p1 = tmp_reg_2392;

assign zext_ln67_11_fu_1817_p1 = $unsigned(tmp_2_reg_2414);

assign zext_ln67_2_fu_1411_p1 = tmp_12_fu_1398_p9;

assign zext_ln67_4_fu_1468_p1 = tmp_14_fu_1457_p7;

assign zext_ln67_9_fu_1789_p1 = tmp_16_fu_1780_p5;

assign zext_ln67_fu_1356_p1 = tmp_10_fu_1342_p11;

endmodule //fiat_25519_carry_mul_fiat_25519_carry_mul_Pipeline_VITIS_LOOP_39_1
