// ==============================================================
// Generated by Vitis HLS v2023.1.1
// Copyright 1986-2022 Xilinx, Inc. All Rights Reserved.
// Copyright 2022-2023 Advanced Micro Devices, Inc. All Rights Reserved.
// ==============================================================

`timescale 1 ns / 1 ps 

module test_test_Pipeline_VITIS_LOOP_173_27 (
        ap_clk,
        ap_rst,
        ap_start,
        ap_done,
        ap_idle,
        ap_ready,
        add245355_reload,
        arg1_r_9_reload,
        arg1_r_10_reload,
        arg1_r_11_reload,
        arg1_r_12_reload,
        arg1_r_13_reload,
        arg1_r_14_reload,
        arg1_r_15_reload,
        arg2_r_reload,
        arg2_r_1_reload,
        arg2_r_2_reload,
        arg2_r_3_reload,
        arg2_r_4_reload,
        arg2_r_5_reload,
        arg2_r_6_reload,
        arg1_r_8_reload,
        arg2_r_7_reload,
        arg1_r_7_reload,
        arg2_r_8_reload,
        add385_2342_out,
        add385_2342_out_ap_vld
);

parameter    ap_ST_fsm_pp0_stage0 = 1'd1;

input   ap_clk;
input   ap_rst;
input   ap_start;
output   ap_done;
output   ap_idle;
output   ap_ready;
input  [63:0] add245355_reload;
input  [31:0] arg1_r_9_reload;
input  [31:0] arg1_r_10_reload;
input  [31:0] arg1_r_11_reload;
input  [31:0] arg1_r_12_reload;
input  [31:0] arg1_r_13_reload;
input  [31:0] arg1_r_14_reload;
input  [31:0] arg1_r_15_reload;
input  [31:0] arg2_r_reload;
input  [31:0] arg2_r_1_reload;
input  [31:0] arg2_r_2_reload;
input  [31:0] arg2_r_3_reload;
input  [31:0] arg2_r_4_reload;
input  [31:0] arg2_r_5_reload;
input  [31:0] arg2_r_6_reload;
input  [31:0] arg1_r_8_reload;
input  [31:0] arg2_r_7_reload;
input  [31:0] arg1_r_7_reload;
input  [31:0] arg2_r_8_reload;
output  [63:0] add385_2342_out;
output   add385_2342_out_ap_vld;

reg ap_idle;
reg add385_2342_out_ap_vld;

(* fsm_encoding = "none" *) reg   [0:0] ap_CS_fsm;
wire    ap_CS_fsm_pp0_stage0;
wire    ap_enable_reg_pp0_iter0;
reg    ap_enable_reg_pp0_iter1;
reg    ap_idle_pp0;
wire    ap_block_state1_pp0_stage0_iter0;
wire    ap_block_state2_pp0_stage0_iter1;
wire    ap_block_pp0_stage0_subdone;
wire   [0:0] tmp_fu_243_p3;
reg    ap_condition_exit_pp0_iter1_stage0;
wire    ap_loop_exit_ready;
reg    ap_ready_int;
wire    ap_block_pp0_stage0_11001;
reg   [63:0] add385_2342_fu_80;
wire   [63:0] add_ln179_3_fu_441_p2;
wire    ap_loop_init;
wire    ap_block_pp0_stage0;
reg   [3:0] i_fu_84;
wire   [3:0] add_ln173_fu_447_p2;
reg   [3:0] k_fu_88;
wire   [3:0] add_ln179_fu_405_p2;
wire    ap_block_pp0_stage0_01001;
wire   [31:0] mul_ln179_fu_213_p0;
wire   [31:0] mul_ln179_fu_213_p1;
wire   [31:0] mul_ln179_1_fu_217_p0;
wire   [31:0] mul_ln179_1_fu_217_p1;
wire   [31:0] mul_ln179_2_fu_221_p0;
wire   [31:0] mul_ln179_2_fu_221_p1;
wire   [31:0] tmp_s_fu_261_p18;
wire   [2:0] trunc_ln35_fu_257_p1;
wire   [31:0] tmp_65_fu_297_p9;
wire   [31:0] tmp_66_fu_315_p18;
wire   [31:0] tmp_67_fu_351_p9;
wire   [31:0] tmp_68_fu_369_p18;
wire   [31:0] tmp_69_fu_411_p9;
wire   [63:0] mul_ln179_2_fu_221_p2;
wire   [63:0] mul_ln179_fu_213_p2;
wire   [63:0] add_ln179_1_fu_429_p2;
wire   [63:0] mul_ln179_1_fu_217_p2;
wire   [63:0] add_ln179_2_fu_435_p2;
reg    ap_done_reg;
wire    ap_continue_int;
reg    ap_done_int;
reg   [0:0] ap_NS_fsm;
wire    ap_enable_pp0;
wire    ap_start_int;
wire   [63:0] mul_ln179_1_fu_217_p00;
wire   [63:0] mul_ln179_1_fu_217_p10;
wire   [63:0] mul_ln179_2_fu_221_p00;
wire   [63:0] mul_ln179_2_fu_221_p10;
wire   [63:0] mul_ln179_fu_213_p00;
wire   [63:0] mul_ln179_fu_213_p10;
wire    ap_ce_reg;

// power-on initialization
initial begin
#0 ap_CS_fsm = 1'd1;
#0 ap_enable_reg_pp0_iter1 = 1'b0;
#0 ap_done_reg = 1'b0;
end

test_mul_32ns_32ns_64_1_1 #(
    .ID( 1 ),
    .NUM_STAGE( 1 ),
    .din0_WIDTH( 32 ),
    .din1_WIDTH( 32 ),
    .dout_WIDTH( 64 ))
mul_32ns_32ns_64_1_1_U397(
    .din0(mul_ln179_fu_213_p0),
    .din1(mul_ln179_fu_213_p1),
    .dout(mul_ln179_fu_213_p2)
);

test_mul_32ns_32ns_64_1_1 #(
    .ID( 1 ),
    .NUM_STAGE( 1 ),
    .din0_WIDTH( 32 ),
    .din1_WIDTH( 32 ),
    .dout_WIDTH( 64 ))
mul_32ns_32ns_64_1_1_U398(
    .din0(mul_ln179_1_fu_217_p0),
    .din1(mul_ln179_1_fu_217_p1),
    .dout(mul_ln179_1_fu_217_p2)
);

test_mul_32ns_32ns_64_1_1 #(
    .ID( 1 ),
    .NUM_STAGE( 1 ),
    .din0_WIDTH( 32 ),
    .din1_WIDTH( 32 ),
    .dout_WIDTH( 64 ))
mul_32ns_32ns_64_1_1_U399(
    .din0(mul_ln179_2_fu_221_p0),
    .din1(mul_ln179_2_fu_221_p1),
    .dout(mul_ln179_2_fu_221_p2)
);

test_mux_16_4_32_1_1 #(
    .ID( 1 ),
    .NUM_STAGE( 1 ),
    .din0_WIDTH( 32 ),
    .din1_WIDTH( 32 ),
    .din2_WIDTH( 32 ),
    .din3_WIDTH( 32 ),
    .din4_WIDTH( 32 ),
    .din5_WIDTH( 32 ),
    .din6_WIDTH( 32 ),
    .din7_WIDTH( 32 ),
    .din8_WIDTH( 32 ),
    .din9_WIDTH( 32 ),
    .din10_WIDTH( 32 ),
    .din11_WIDTH( 32 ),
    .din12_WIDTH( 32 ),
    .din13_WIDTH( 32 ),
    .din14_WIDTH( 32 ),
    .din15_WIDTH( 32 ),
    .din16_WIDTH( 4 ),
    .dout_WIDTH( 32 ))
mux_16_4_32_1_1_U400(
    .din0(32'd0),
    .din1(32'd0),
    .din2(32'd0),
    .din3(32'd0),
    .din4(32'd0),
    .din5(32'd0),
    .din6(32'd0),
    .din7(32'd0),
    .din8(32'd0),
    .din9(arg1_r_9_reload),
    .din10(arg1_r_10_reload),
    .din11(arg1_r_11_reload),
    .din12(arg1_r_12_reload),
    .din13(arg1_r_13_reload),
    .din14(arg1_r_14_reload),
    .din15(arg1_r_15_reload),
    .din16(i_fu_84),
    .dout(tmp_s_fu_261_p18)
);

test_mux_7_3_32_1_1 #(
    .ID( 1 ),
    .NUM_STAGE( 1 ),
    .din0_WIDTH( 32 ),
    .din1_WIDTH( 32 ),
    .din2_WIDTH( 32 ),
    .din3_WIDTH( 32 ),
    .din4_WIDTH( 32 ),
    .din5_WIDTH( 32 ),
    .din6_WIDTH( 32 ),
    .din7_WIDTH( 3 ),
    .dout_WIDTH( 32 ))
mux_7_3_32_1_1_U401(
    .din0(arg2_r_reload),
    .din1(arg2_r_1_reload),
    .din2(arg2_r_2_reload),
    .din3(arg2_r_3_reload),
    .din4(arg2_r_4_reload),
    .din5(arg2_r_5_reload),
    .din6(arg2_r_6_reload),
    .din7(trunc_ln35_fu_257_p1),
    .dout(tmp_65_fu_297_p9)
);

test_mux_16_4_32_1_1 #(
    .ID( 1 ),
    .NUM_STAGE( 1 ),
    .din0_WIDTH( 32 ),
    .din1_WIDTH( 32 ),
    .din2_WIDTH( 32 ),
    .din3_WIDTH( 32 ),
    .din4_WIDTH( 32 ),
    .din5_WIDTH( 32 ),
    .din6_WIDTH( 32 ),
    .din7_WIDTH( 32 ),
    .din8_WIDTH( 32 ),
    .din9_WIDTH( 32 ),
    .din10_WIDTH( 32 ),
    .din11_WIDTH( 32 ),
    .din12_WIDTH( 32 ),
    .din13_WIDTH( 32 ),
    .din14_WIDTH( 32 ),
    .din15_WIDTH( 32 ),
    .din16_WIDTH( 4 ),
    .dout_WIDTH( 32 ))
mux_16_4_32_1_1_U402(
    .din0(32'd0),
    .din1(32'd0),
    .din2(32'd0),
    .din3(32'd0),
    .din4(32'd0),
    .din5(32'd0),
    .din6(32'd0),
    .din7(32'd0),
    .din8(32'd0),
    .din9(arg1_r_8_reload),
    .din10(arg1_r_9_reload),
    .din11(arg1_r_10_reload),
    .din12(arg1_r_11_reload),
    .din13(arg1_r_12_reload),
    .din14(arg1_r_13_reload),
    .din15(arg1_r_14_reload),
    .din16(i_fu_84),
    .dout(tmp_66_fu_315_p18)
);

test_mux_7_3_32_1_1 #(
    .ID( 1 ),
    .NUM_STAGE( 1 ),
    .din0_WIDTH( 32 ),
    .din1_WIDTH( 32 ),
    .din2_WIDTH( 32 ),
    .din3_WIDTH( 32 ),
    .din4_WIDTH( 32 ),
    .din5_WIDTH( 32 ),
    .din6_WIDTH( 32 ),
    .din7_WIDTH( 3 ),
    .dout_WIDTH( 32 ))
mux_7_3_32_1_1_U403(
    .din0(arg2_r_1_reload),
    .din1(arg2_r_2_reload),
    .din2(arg2_r_3_reload),
    .din3(arg2_r_4_reload),
    .din4(arg2_r_5_reload),
    .din5(arg2_r_6_reload),
    .din6(arg2_r_7_reload),
    .din7(trunc_ln35_fu_257_p1),
    .dout(tmp_67_fu_351_p9)
);

test_mux_16_4_32_1_1 #(
    .ID( 1 ),
    .NUM_STAGE( 1 ),
    .din0_WIDTH( 32 ),
    .din1_WIDTH( 32 ),
    .din2_WIDTH( 32 ),
    .din3_WIDTH( 32 ),
    .din4_WIDTH( 32 ),
    .din5_WIDTH( 32 ),
    .din6_WIDTH( 32 ),
    .din7_WIDTH( 32 ),
    .din8_WIDTH( 32 ),
    .din9_WIDTH( 32 ),
    .din10_WIDTH( 32 ),
    .din11_WIDTH( 32 ),
    .din12_WIDTH( 32 ),
    .din13_WIDTH( 32 ),
    .din14_WIDTH( 32 ),
    .din15_WIDTH( 32 ),
    .din16_WIDTH( 4 ),
    .dout_WIDTH( 32 ))
mux_16_4_32_1_1_U404(
    .din0(32'd0),
    .din1(32'd0),
    .din2(32'd0),
    .din3(32'd0),
    .din4(32'd0),
    .din5(32'd0),
    .din6(32'd0),
    .din7(32'd0),
    .din8(32'd0),
    .din9(arg1_r_7_reload),
    .din10(arg1_r_8_reload),
    .din11(arg1_r_9_reload),
    .din12(arg1_r_10_reload),
    .din13(arg1_r_11_reload),
    .din14(arg1_r_12_reload),
    .din15(arg1_r_13_reload),
    .din16(i_fu_84),
    .dout(tmp_68_fu_369_p18)
);

test_mux_7_3_32_1_1 #(
    .ID( 1 ),
    .NUM_STAGE( 1 ),
    .din0_WIDTH( 32 ),
    .din1_WIDTH( 32 ),
    .din2_WIDTH( 32 ),
    .din3_WIDTH( 32 ),
    .din4_WIDTH( 32 ),
    .din5_WIDTH( 32 ),
    .din6_WIDTH( 32 ),
    .din7_WIDTH( 3 ),
    .dout_WIDTH( 32 ))
mux_7_3_32_1_1_U405(
    .din0(arg2_r_2_reload),
    .din1(arg2_r_3_reload),
    .din2(arg2_r_4_reload),
    .din3(arg2_r_5_reload),
    .din4(arg2_r_6_reload),
    .din5(arg2_r_7_reload),
    .din6(arg2_r_8_reload),
    .din7(trunc_ln35_fu_257_p1),
    .dout(tmp_69_fu_411_p9)
);

test_flow_control_loop_pipe_sequential_init flow_control_loop_pipe_sequential_init_U(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst),
    .ap_start(ap_start),
    .ap_ready(ap_ready),
    .ap_done(ap_done),
    .ap_start_int(ap_start_int),
    .ap_loop_init(ap_loop_init),
    .ap_ready_int(ap_ready_int),
    .ap_loop_exit_ready(ap_condition_exit_pp0_iter1_stage0),
    .ap_loop_exit_done(ap_done_int),
    .ap_continue_int(ap_continue_int),
    .ap_done_int(ap_done_int)
);

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_CS_fsm <= ap_ST_fsm_pp0_stage0;
    end else begin
        ap_CS_fsm <= ap_NS_fsm;
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_done_reg <= 1'b0;
    end else begin
        if ((ap_continue_int == 1'b1)) begin
            ap_done_reg <= 1'b0;
        end else if (((ap_loop_exit_ready == 1'b1) & (1'b0 == ap_block_pp0_stage0_subdone) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
            ap_done_reg <= 1'b1;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter1 <= 1'b0;
    end else begin
        if ((1'b1 == ap_condition_exit_pp0_iter1_stage0)) begin
            ap_enable_reg_pp0_iter1 <= 1'b0;
        end else if (((1'b0 == ap_block_pp0_stage0_subdone) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
            ap_enable_reg_pp0_iter1 <= ap_start_int;
        end
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        if ((ap_loop_init == 1'b1)) begin
            add385_2342_fu_80 <= add245355_reload;
        end else if (((tmp_fu_243_p3 == 1'd1) & (ap_enable_reg_pp0_iter1 == 1'b1))) begin
            add385_2342_fu_80 <= add_ln179_3_fu_441_p2;
        end
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        if ((ap_loop_init == 1'b1)) begin
            i_fu_84 <= 4'd15;
        end else if (((tmp_fu_243_p3 == 1'd1) & (ap_enable_reg_pp0_iter1 == 1'b1))) begin
            i_fu_84 <= add_ln173_fu_447_p2;
        end
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        if ((ap_loop_init == 1'b1)) begin
            k_fu_88 <= 4'd0;
        end else if (((tmp_fu_243_p3 == 1'd1) & (ap_enable_reg_pp0_iter1 == 1'b1))) begin
            k_fu_88 <= add_ln179_fu_405_p2;
        end
    end
end

always @ (*) begin
    if (((tmp_fu_243_p3 == 1'd0) & (1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        add385_2342_out_ap_vld = 1'b1;
    end else begin
        add385_2342_out_ap_vld = 1'b0;
    end
end

always @ (*) begin
    if (((tmp_fu_243_p3 == 1'd0) & (1'b0 == ap_block_pp0_stage0_subdone) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        ap_condition_exit_pp0_iter1_stage0 = 1'b1;
    end else begin
        ap_condition_exit_pp0_iter1_stage0 = 1'b0;
    end
end

always @ (*) begin
    if (((ap_loop_exit_ready == 1'b1) & (1'b0 == ap_block_pp0_stage0_subdone) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        ap_done_int = 1'b1;
    end else begin
        ap_done_int = ap_done_reg;
    end
end

always @ (*) begin
    if (((ap_start_int == 1'b0) & (ap_idle_pp0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        ap_idle = 1'b1;
    end else begin
        ap_idle = 1'b0;
    end
end

always @ (*) begin
    if (((ap_enable_reg_pp0_iter1 == 1'b0) & (ap_enable_reg_pp0_iter0 == 1'b0))) begin
        ap_idle_pp0 = 1'b1;
    end else begin
        ap_idle_pp0 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_subdone) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        ap_ready_int = 1'b1;
    end else begin
        ap_ready_int = 1'b0;
    end
end

always @ (*) begin
    case (ap_CS_fsm)
        ap_ST_fsm_pp0_stage0 : begin
            ap_NS_fsm = ap_ST_fsm_pp0_stage0;
        end
        default : begin
            ap_NS_fsm = 'bx;
        end
    endcase
end

assign add385_2342_out = add385_2342_fu_80;

assign add_ln173_fu_447_p2 = ($signed(i_fu_84) + $signed(4'd13));

assign add_ln179_1_fu_429_p2 = (mul_ln179_2_fu_221_p2 + mul_ln179_fu_213_p2);

assign add_ln179_2_fu_435_p2 = (add_ln179_1_fu_429_p2 + mul_ln179_1_fu_217_p2);

assign add_ln179_3_fu_441_p2 = (add385_2342_fu_80 + add_ln179_2_fu_435_p2);

assign add_ln179_fu_405_p2 = (k_fu_88 + 4'd3);

assign ap_CS_fsm_pp0_stage0 = ap_CS_fsm[32'd0];

assign ap_block_pp0_stage0 = ~(1'b1 == 1'b1);

assign ap_block_pp0_stage0_01001 = ~(1'b1 == 1'b1);

assign ap_block_pp0_stage0_11001 = ~(1'b1 == 1'b1);

assign ap_block_pp0_stage0_subdone = ~(1'b1 == 1'b1);

assign ap_block_state1_pp0_stage0_iter0 = ~(1'b1 == 1'b1);

assign ap_block_state2_pp0_stage0_iter1 = ~(1'b1 == 1'b1);

assign ap_enable_pp0 = (ap_idle_pp0 ^ 1'b1);

assign ap_enable_reg_pp0_iter0 = ap_start_int;

assign ap_loop_exit_ready = ap_condition_exit_pp0_iter1_stage0;

assign mul_ln179_1_fu_217_p0 = mul_ln179_1_fu_217_p00;

assign mul_ln179_1_fu_217_p00 = tmp_65_fu_297_p9;

assign mul_ln179_1_fu_217_p1 = mul_ln179_1_fu_217_p10;

assign mul_ln179_1_fu_217_p10 = tmp_s_fu_261_p18;

assign mul_ln179_2_fu_221_p0 = mul_ln179_2_fu_221_p00;

assign mul_ln179_2_fu_221_p00 = tmp_67_fu_351_p9;

assign mul_ln179_2_fu_221_p1 = mul_ln179_2_fu_221_p10;

assign mul_ln179_2_fu_221_p10 = tmp_66_fu_315_p18;

assign mul_ln179_fu_213_p0 = mul_ln179_fu_213_p00;

assign mul_ln179_fu_213_p00 = tmp_69_fu_411_p9;

assign mul_ln179_fu_213_p1 = mul_ln179_fu_213_p10;

assign mul_ln179_fu_213_p10 = tmp_68_fu_369_p18;

assign tmp_fu_243_p3 = i_fu_84[32'd3];

assign trunc_ln35_fu_257_p1 = k_fu_88[2:0];

endmodule //test_test_Pipeline_VITIS_LOOP_173_27
